static const char *default_text_en =
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt nibh quis semper malesuada. Mauris sit amet metus sed tellus gravida maximus\n"
"sit amet a enim. Morbi et lorem congue, aliquam lorem vitae, condimentum erat. Mauris aliquet, sapien consequat blandit mattis, velit ante molestie\n"
"mi, ac condimentum justo leo sed odio. Curabitur at suscipit quam. Ut ac convallis ante, at sollicitudin sapien. Nulla pellentesque felis id mi\n"
"blandit dictum. Phasellus ultrices, odio non volutpat tincidunt, neque quam tristique lacus, nec gravida nulla ante id risus. Nulla sit amet bibendum\n"
"lectus, sed bibendum lectus. Vivamus ultrices metus sit amet sapien posuere volutpat. Suspendisse luctus non mauris nec iaculis. Duis mattis enim\n"
"libero, ac malesuada tortor gravida tempor. Cras sagittis felis at sollicitudin fermentum. Duis et ipsum bibendum, viverra felis quis, consectetur\n"
"lacus.  Donec vulputate risus imperdiet, tincidunt purus nec, vestibulum lorem. Morbi iaculis tincidunt rutrum. Duis sit amet nulla ut lectus\n"
"efficitur suscipit. Curabitur urna turpis, congue lacinia varius vitae, interdum vel dolor. Vestibulum sit amet suscipit arcu, sit amet tincidunt\n"
"ipsum. Maecenas feugiat ante vel fermentum viverra. Sed aliquam sem ac quam bibendum, sit amet fringilla augue pharetra. Morbi scelerisque tempus\n"
"purus, interdum tempor est pulvinar bibendum. Duis tincidunt dictum ante vel sodales. Fusce quis cursus metus. Pellentesque mi mauris, tincidunt ut\n"
"orci ut, interdum dapibus dolor. Aliquam blandit, nisl et rhoncus laoreet, tellus nulla blandit tellus, sit amet cursus magna enim nec ante. Integer\n"
"venenatis a est sed hendrerit.  Proin id porttitor turpis, aliquam tempus ex. Morbi tristique, felis ut aliquet luctus, orci tortor sodales sem, vel\n"
"imperdiet justo tortor sit amet arcu. Quisque ipsum sem, lacinia in fermentum eu, maximus in lectus. Pellentesque quis scelerisque neque, eget\n"
"ultricies ligula. Etiam accumsan orci mi, ut blandit nibh viverra quis. Pellentesque tincidunt auctor dictum. Integer tincidunt neque at enim\n"
"ultrices, in accumsan augue elementum. Sed placerat eros leo, ac venenatis metus dignissim vel. Suspendisse mauris sem, pulvinar id purus non,\n"
"hendrerit pretium sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla accumsan massa id nulla viverra\n"
"semper. Aliquam sit amet neque vitae diam rhoncus feugiat. Etiam tellus purus, rhoncus id enim a, fermentum volutpat neque. Vestibulum tortor augue,\n"
"dapibus at varius sed, varius at nisl. Ut pharetra elementum varius.  Nulla molestie, urna sit amet euismod venenatis, nunc magna bibendum augue,\n"
"vitae elementum augue elit eget urna. Morbi a leo at sapien tempor varius sit amet venenatis metus. Sed ac pellentesque turpis, quis malesuada ligula.\n"
"Cras quis ex mattis, ultricies nibh ac, vestibulum velit. Sed sed sagittis libero, at consectetur massa. Cras quis risus nunc. Curabitur vitae odio\n"
"laoreet, sodales sem eu, fermentum risus. Quisque laoreet felis eu mattis laoreet. Phasellus auctor velit ut varius accumsan. Sed molestie bibendum mi\n"
"varius auctor. Vestibulum iaculis, lacus ut mattis convallis, turpis purus cursus nibh, nec ullamcorper dolor nibh eget nunc. Nam lacinia justo ac\n"
"vestibulum lacinia. Nulla vestibulum eu urna a sodales. Aliquam blandit congue lacus vitae ornare.  Nulla bibendum vehicula tortor eu vestibulum.\n"
"Mauris nec pretium est. Pellentesque faucibus quam et est sollicitudin, quis condimentum justo placerat. Etiam urna elit, porttitor sodales dui\n"
"congue, maximus sodales dolor. Proin lacinia diam quis libero molestie viverra. Pellentesque tortor mauris, sodales vel luctus non, euismod eu risus.\n"
"Nulla sed condimentum ex. Morbi ac mi quis felis laoreet mattis. Fusce nec quam orci. Morbi pretium quis risus a tincidunt. Phasellus accumsan\n"
"suscipit nisi sed viverra. Vestibulum eu vulputate lorem. Nullam fermentum turpis eget nulla rutrum egestas. Sed tortor nisi, consectetur a semper ut,\n"
"lacinia in lectus. Phasellus finibus at diam nec interdum.  Nunc mollis congue enim, et tempor neque dapibus quis. Nunc a egestas quam, vitae tempor\n"
"mi. Sed at lobortis neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam blandit mi sit amet\n"
"ipsum accumsan, eget euismod nulla facilisis. Morbi imperdiet ex massa, in porttitor nibh posuere ut. Curabitur bibendum lorem id ultricies placerat.\n"
"Aenean tincidunt malesuada mauris, sit amet rhoncus odio ornare ac. Morbi venenatis turpis non nulla tincidunt, bibendum tincidunt quam ultricies. \n"
"Donec dictum, lorem eget commodo malesuada, risus nisi ornare augue, feugiat accumsan dui massa eu ipsum. Mauris aliquam sapien id felis faucibus\n"
"ornare. Nullam eleifend felis vel metus rutrum mollis. Quisque posuere eros vitae imperdiet dapibus. Suspendisse quis est laoreet, faucibus lectus at,\n"
"mattis est. Vestibulum nec neque ut ante auctor luctus. Nunc posuere vulputate egestas. Quisque sit amet sodales erat, ac suscipit lorem. Ut auctor\n"
"dapibus efficitur. Phasellus tincidunt cursus neque in ultrices. Sed pretium viverra felis vitae aliquet. Vivamus at quam libero. Phasellus mattis\n"
"orci ut egestas finibus. Suspendisse mattis maximus consequat. Ut id aliquam lectus.  Maecenas ut libero in nulla tempus accumsan at at tellus.\n"
"Quisque a nibh quis ligula pharetra vehicula id et ante. Pellentesque et nisl in lectus commodo sollicitudin non quis lectus. Vestibulum varius leo at\n"
"diam fringilla, nec vulputate diam pellentesque. Curabitur id nisl in nibh sollicitudin vestibulum non sit amet odio. Nunc pulvinar lectus ac est\n"
"sagittis mollis. Nunc vel consectetur nulla, sit amet eleifend elit. Etiam volutpat, ligula id cursus posuere, est lacus sagittis purus, scelerisque\n"
"tempus sem lectus tempor nisi. Curabitur scelerisque leo et neque ultricies semper. Sed in efficitur urna. Aliquam tempus cursus tortor. Sed feugiat\n"
"mi elit, id ullamcorper nulla ullamcorper vitae. Suspendisse rutrum ornare orci, eget facilisis nisi ornare et. Aenean sed leo vitae lorem congue\n"
"lobortis. Nunc vel dui condimentum, sagittis sapien ac, ultricies odio. Suspendisse elementum iaculis commodo.  Phasellus pellentesque purus nec nisl\n"
"pretium eleifend. Suspendisse a imperdiet urna. Fusce eleifend et nunc at elementum. Morbi imperdiet varius mattis. Cras pharetra urna nulla, gravida\n"
"sodales orci blandit et. Nulla dignissim eleifend tempus. Vivamus placerat tristique purus et facilisis. In eget maximus urna. Mauris ut commodo elit.\n"
"Aliquam erat volutpat. Donec efficitur augue vitae nisi suscipit, vel aliquet sem posuere. Ut placerat ullamcorper lorem, eget consequat nunc\n"
"ultricies nec. Nulla scelerisque ex non velit efficitur imperdiet. Aliquam faucibus augue vel rhoncus feugiat. Aenean hendrerit nunc sem, ac hendrerit\n"
"tortor fringilla sed.  Morbi lorem massa, dictum at maximus vitae, dictum et mi. Nullam ante elit, ultrices tincidunt tempor quis, aliquam ut lacus.\n"
"Donec ut aliquet purus. Sed dolor mi, rhoncus auctor tristique ac, lobortis non urna. Sed tempor leo ut finibus mattis. Aenean fermentum augue eget\n"
"nisi aliquet feugiat. Donec convallis laoreet nulla id malesuada. Vestibulum in congue enim, non sagittis massa. Ut et euismod nibh, eu euismod leo.\n"
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.  Cras sodales purus nec ligula egestas cursus. Sed\n"
"gravida, elit non eleifend semper, ex erat ultricies augue, nec suscipit velit metus in augue. Nulla dapibus, ante a aliquam cursus, mi purus lobortis\n"
"purus, sit amet feugiat neque sapien at mauris. Vivamus mattis sagittis purus, quis viverra dolor mollis nec. Pellentesque habitant morbi tristique\n"
"senectus et netus et malesuada fames ac turpis egestas. Fusce in semper justo, eget mattis magna. Donec libero augue, aliquam eget mi at, laoreet\n"
"sodales metus.  Etiam gravida, libero eu pellentesque imperdiet, nulla dolor scelerisque tortor, vitae placerat est risus non metus. Etiam vel laoreet\n"
"est. Ut posuere turpis facilisis, faucibus magna nec, ornare augue. Pellentesque auctor feugiat ornare. Etiam vulputate vitae odio et lacinia. Aenean\n"
"semper purus vitae erat tincidunt volutpat. Sed et laoreet nulla, eu condimentum arcu.  Maecenas magna arcu, condimentum ut elementum vitae, laoreet\n"
"sed justo. Maecenas bibendum lacus vel blandit tincidunt. Praesent mattis, eros eget auctor malesuada, felis ligula egestas eros, at lacinia dolor\n"
"lacus sed arcu. Praesent lectus lacus, rhoncus ultricies facilisis vel, tristique pellentesque eros. Donec et justo placerat, finibus lectus id,\n"
"mattis augue. Nam consequat, felis a commodo varius, odio erat viverra urna, mollis sodales nibh lectus non turpis. Maecenas quis egestas risus, eget\n"
"lobortis dui. Sed pellentesque vitae neque non condimentum. Proin eu maximus magna, ac posuere libero. Maecenas porta interdum metus eu hendrerit.\n"
"Integer ut blandit risus. Maecenas facilisis consectetur dolor a mattis. Morbi elementum tincidunt turpis, vel tempus est mattis vel.  Morbi et\n"
"ultrices velit, at dapibus neque. Vestibulum dictum in mi et rhoncus. In congue, elit vel ultricies maximus, arcu augue venenatis neque, sed imperdiet\n"
"purus leo et risus. Quisque tincidunt sapien felis, vitae elementum erat aliquet in. Curabitur mauris nibh, dictum sollicitudin dolor ut, accumsan\n"
"luctus nulla. Aenean quis diam quam. Etiam viverra odio at felis tincidunt laoreet. Proin euismod non lectus sit amet lacinia. Proin aliquet mauris et\n"
"dui consectetur sagittis. Ut tempus fringilla odio, vitae scelerisque neque efficitur ut. Quisque a nulla pulvinar, varius dolor sed, eleifend magna. \n"
"Vivamus eu neque pulvinar, accumsan odio venenatis, mollis leo. Morbi aliquet ac dolor sed lobortis. Maecenas urna sapien, volutpat non sagittis in,\n"
"tempor eget enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed mollis porta lectus, id lobortis metus elementum vitae. Nullam non\n"
"nulla sed risus rhoncus tempor. Nullam id quam hendrerit, dictum purus ut, maximus ipsum. Cras auct\n"
;
