static const char *demo_fragment_glsl =
"/*\n"
" * Copyright 2026 Behdad Esfahbod. All Rights Reserved.\n"
" */\n"
"\n"
"uniform float u_gamma;\n"
"uniform float u_debug;\n"
"uniform float u_stem_darkening;\n"
"uniform vec4 u_foreground;\n"
"\n"
"in vec2 v_texcoord;\n"
"flat in uint v_glyphLoc;\n"
"\n"
"out vec4 fragColor;\n"
"\n"
"void main ()\n"
"{\n"
"#ifdef HB_GPU_DEMO_DRAW\n"
"  /* Fast path for fonts with no color paint: call the Slug\n"
"   * coverage sampler directly and tint by the foreground uniform.\n"
"   * Smaller shader program, better occupancy. */\n"
"  float cov = hb_gpu_draw (v_texcoord, v_glyphLoc);\n"
"  vec4 c = vec4 (u_foreground.rgb * u_foreground.a, u_foreground.a) * cov;\n"
"#else\n"
"  /* Paint interpreter -- handles monochrome via a synthesized\n"
"   * LAYER_SOLID and color paint trees otherwise. */\n"
"  vec4 c = hb_gpu_paint (v_texcoord, v_glyphLoc, u_foreground);\n"
"#endif\n"
"\n"
"  /* Stem darkening: scale the premultiplied value by the\n"
"   * alpha-channel darkening ratio so RGB and A stay in lockstep. */\n"
"  if (u_stem_darkening > 0.0 && c.a > 0.0)\n"
"  {\n"
"    float darkened = hb_gpu_stem_darken (c.a,\n"
"      dot (u_foreground.rgb, vec3 (1.0 / 3.0)),\n"
"      1.0 / max (fwidth (v_texcoord).x, fwidth (v_texcoord).y));\n"
"    c *= darkened / c.a;\n"
"  }\n"
"\n"
"  if (u_gamma != 1.0)\n"
"    c.a = pow (c.a, u_gamma);\n"
"\n"
"  if (u_debug > 0.0)\n"
"  {\n"
"    ivec2 counts = _hb_gpu_curve_counts (v_texcoord, v_glyphLoc);\n"
"    float r = clamp (float (counts.x) / 8.0, 0.0, 1.0);\n"
"    float g = clamp (float (counts.y) / 8.0, 0.0, 1.0);\n"
"    fragColor = vec4 (r, g, c.a, max (max (r, g), c.a));\n"
"    return;\n"
"  }\n"
"\n"
"  fragColor = c;\n"
"}\n"
;
