static const char *demo_fragment_glsl =
"uniform float u_gamma;\n"
"uniform float u_debug;\n"
"uniform vec4 u_foreground;\n"
"\n"
"in vec2 v_texcoord;\n"
"flat in uint v_glyphLoc;\n"
"\n"
"out vec4 fragColor;\n"
"\n"
"void main ()\n"
"{\n"
"  float coverage = hb_gpu_render (v_texcoord, v_glyphLoc);\n"
"\n"
"  if (u_gamma != 1.0)\n"
"    coverage = pow (coverage, u_gamma);\n"
"\n"
"  if (u_debug > 0.0)\n"
"  {\n"
"    ivec2 counts = _hb_gpu_curve_counts (v_texcoord, v_glyphLoc);\n"
"    float r = clamp (float (counts.x) / 8.0, 0.0, 1.0);\n"
"    float g = clamp (float (counts.y) / 8.0, 0.0, 1.0);\n"
"    /* Blue text on black, then add R/G heatmap */\n"
"    fragColor = vec4 (r, g, coverage, 1.0);\n"
"    return;\n"
"  }\n"
"\n"
"  fragColor = vec4 (u_foreground.rgb, u_foreground.a * coverage);\n"
"}\n"
;
