static const char *demo_fragment_glsl =
"/*\n"
" * Copyright 2026 Behdad Esfahbod. All Rights Reserved.\n"
" */\n"
"\n"
"uniform float u_gamma;\n"
"uniform float u_debug;\n"
"uniform float u_stem_darkening;\n"
"uniform vec4 u_foreground;\n"
"\n"
"in vec2 v_texcoord;\n"
"flat in uint v_glyphLoc;\n"
"\n"
"out vec4 fragColor;\n"
"\n"
"void main ()\n"
"{\n"
"  /* The paint interpreter returns a premultiplied RGBA.  For\n"
"   * non-color glyphs the encoder synthesizes a single\n"
"   * LAYER_SOLID with is_foreground=true, so the result is\n"
"   * u_foreground * coverage -- same visual as the old draw\n"
"   * path.  For COLRv0 glyphs it returns the composited color. */\n"
"  vec4 c = hb_gpu_paint (v_texcoord, v_glyphLoc, u_foreground);\n"
"\n"
"  if (u_gamma != 1.0)\n"
"    c.a = pow (c.a, u_gamma);\n"
"\n"
"  if (u_debug > 0.0)\n"
"  {\n"
"    ivec2 counts = _hb_gpu_curve_counts (v_texcoord, v_glyphLoc);\n"
"    float r = clamp (float (counts.x) / 8.0, 0.0, 1.0);\n"
"    float g = clamp (float (counts.y) / 8.0, 0.0, 1.0);\n"
"    fragColor = vec4 (r, g, c.a, max (max (r, g), c.a));\n"
"    return;\n"
"  }\n"
"\n"
"  fragColor = c;\n"
"}\n"
;
