#!/bin/bash

trap "exit" INT

if which svgo 2>/dev/null >/dev/null; then
	SVGO=svgo
else
	echo "'svgo' not found"
	exit 2
fi

if test "x$1" == 'x-o'; then
	shift
	dir=$1
	shift
	mkdir -p "$dir"
else
	dir=`mktemp -d`
	echo "Output in $dir"
fi

hb_view=$1
shift
if ! echo "$hb_view" | grep -q 'hb-view'; then
	echo "Specify hb-view: got '$hb_view'." >&2
	exit 1
fi

fontfile=$1
shift

fontsize=32
variations="wght=400"

BACKEND0=ot
BACKEND1=coretext

echo "Comparing $fontfile with $BACKEND0 and $BACKEND1 backends..."

unicodes="$@"
if test "x$unicodes" == x; then
	unicodes=`hb-info --quiet --list-unicodes "$fontfile" | cut -f1`
fi
status=0
numfails=0
for unicode in $unicodes; do

	echo "Comparing glyph $unicode..."

	DIFF="$dir/$unicode.diff"

	for backend in $BACKEND0 $BACKEND1; do
		$hb_view \
			--font-file "$fontfile" \
			--unicodes $unicode \
			--face-loader=coretext \
			--shaper=coretext \
			--font-funcs=$backend \
			--variations="$variations" \
			--output-format=svg \
			--font-size $fontsize |
		$SVGO - -q -p 0 | \
		sed 's/ /\n/g' > "$dir/$unicode.$backend.svg"
	done

	if diff -u "$dir/$unicode.$BACKEND0.svg" "$dir/$unicode.$BACKEND1.svg" > "$DIFF"; then
		rm -f "$DIFF"
		continue
	fi

	status=1
	numfails=$((numfails+1))
	echo "Charater $unicode differs:" `wc -l < "$DIFF"` lines
done

if test $status -eq 0; then
	echo "All characters are the same."
else
	echo "$numfails characters differ."
	echo "Differences are in $dir"
fi

exit $status
