TESTS = \
	tests/AVAR-1.tests \
	tests/CFF-1.tests \
	tests/CFF2-1.tests \
	tests/CFF-2.tests \
	tests/CMAP-1.tests \
	tests/CMAP-2.tests \
	tests/CVAR-1.tests \
	tests/CVAR-2.tests \
	tests/GLYF-1.tests \
	tests/GPOS-1.tests \
	tests/GPOS-2.tests \
	tests/GPOS-3.tests \
	tests/GPOS-4.tests \
	tests/GPOS-5.tests \
	tests/GSUB-1.tests \
	tests/GSUB-2.tests \
	tests/GVAR-1.tests \
	tests/GVAR-2.tests \
	tests/GVAR-3.tests \
	tests/GVAR-4.tests \
	tests/GVAR-5.tests \
	tests/GVAR-6.tests \
	tests/GVAR-7.tests \
	tests/GVAR-8.tests \
	tests/GVAR-9.tests \
	tests/HVAR-1.tests \
	tests/HVAR-2.tests \
	tests/KERN-1.tests \
	tests/KERN-2.tests \
	tests/MORX-5.tests \
	tests/MORX-6.tests \
	tests/MORX-7.tests \
	tests/MORX-8.tests \
	tests/MORX-9.tests \
	tests/SHBALI-3.tests \
	tests/SHKNDA-1.tests \
	$(NULL)

DISBALED_TESTS = \
	tests/CMAP-3.tests \
	tests/MORX-1.tests \
	tests/MORX-2.tests \
	tests/MORX-3.tests \
	tests/MORX-4.tests \
	tests/SHARAN-1.tests \
	tests/SHBALI-1.tests \
	tests/SHBALI-2.tests \
	tests/SHKNDA-2.tests \
	tests/SHKNDA-3.tests \
	$(NULL)
