#!/usr/bin/env python3

"""usage: ./gen-hebrew-pua.py
"""

import packTab


print ("/* == Start of generated table == */")
print ("/*")
print (" * The following table is generated by running:")
print (" *")
print (" *   ./gen-hebrew-pua.py")
print (" *")
print (" */")
print ()
print ("#ifndef HB_OT_SHAPER_HEBREW_PUA_HH")
print ("#define HB_OT_SHAPER_HEBREW_PUA_HH")
print ()
print ('#include "hb.hh"')
print ()

code = packTab.Code('_hb_hebrew_pua')

with open ("HebrewPUA.txt", encoding='utf-8') as f:
    fields = [l.split('\t') for l in f if l[:1] != '#']
data = {int(fs[1], 16):int(fs[0], 16) for fs in fields}
sol = packTab.pack_table(data, compression=9)
sol.genCode(code, 'map')

code.print_c()

print ()
print ("#endif /* HB_OT_SHAPER_HEBREW_PUA_HH */")
print ()
print ("/* == End of generated table == */")
