static const char *hb_gpu_fragment_wgsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" * Copyright (C) 2017  Eric Lengyel\n"
" *\n"
" * Based on the Slug algorithm by Eric Lengyel:\n"
" * https://github.com/EricLengyel/Slug\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Requires WGSL (WebGPU Shading Language). */\n"
"\n"
"\n"
"const HB_GPU_UNITS_PER_EM: f32 = 4.0;\n"
"const HB_GPU_INV_UNITS: f32 = 1.0 / 4.0;\n"
"\n"
"\n"
"fn _hb_gpu_fetch (hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>,\n"
"                  offset: i32) -> vec4<i32>\n"
"{\n"
"  return (*hb_gpu_atlas)[offset];\n"
"}\n"
"\n"
"\n"
"fn _hb_gpu_calc_root_code (y1: f32, y2: f32, y3: f32) -> u32\n"
"{\n"
"  let i1 = bitcast<u32> (y1) >> 31u;\n"
"  let i2 = bitcast<u32> (y2) >> 30u;\n"
"  let i3 = bitcast<u32> (y3) >> 29u;\n"
"\n"
"  var shift = (i2 & 2u) | (i1 & ~2u);\n"
"  shift = (i3 & 4u) | (shift & ~4u);\n"
"\n"
"  return (0x2E74u >> shift) & 0x0101u;\n"
"}\n"
"\n"
"fn _hb_gpu_solve_horiz_poly (a: vec2f, b: vec2f, p1: vec2f) -> vec2f\n"
"{\n"
"  let ra = 1.0 / a.y;\n"
"  let rb = 0.5 / b.y;\n"
"\n"
"  let d = sqrt (max (b.y * b.y - a.y * p1.y, 0.0));\n"
"  var t1 = (b.y - d) * ra;\n"
"  var t2 = (b.y + d) * ra;\n"
"\n"
"  if (a.y == 0.0) {\n"
"    t1 = p1.y * rb;\n"
"    t2 = t1;\n"
"  }\n"
"\n"
"  return vec2f ((a.x * t1 - b.x * 2.0) * t1 + p1.x,\n"
"                (a.x * t2 - b.x * 2.0) * t2 + p1.x);\n"
"}\n"
"\n"
"fn _hb_gpu_solve_vert_poly (a: vec2f, b: vec2f, p1: vec2f) -> vec2f\n"
"{\n"
"  let ra = 1.0 / a.x;\n"
"  let rb = 0.5 / b.x;\n"
"\n"
"  let d = sqrt (max (b.x * b.x - a.x * p1.x, 0.0));\n"
"  var t1 = (b.x - d) * ra;\n"
"  var t2 = (b.x + d) * ra;\n"
"\n"
"  if (a.x == 0.0) {\n"
"    t1 = p1.x * rb;\n"
"    t2 = t1;\n"
"  }\n"
"\n"
"  return vec2f ((a.y * t1 - b.y * 2.0) * t1 + p1.y,\n"
"                (a.y * t2 - b.y * 2.0) * t2 + p1.y);\n"
"}\n"
"\n"
"fn _hb_gpu_calc_coverage (xcov: f32, ycov: f32, xwgt: f32, ywgt: f32) -> f32\n"
"{\n"
"  let coverage = max (abs (xcov * xwgt + ycov * ywgt) /\n"
"                      max (xwgt + ywgt, 1.0 / 65536.0),\n"
"                      min (abs (xcov), abs (ycov)));\n"
"\n"
"  return clamp (coverage, 0.0, 1.0);\n"
"}\n"
"\n"
"/* Render a glyph and return its coverage in [0, 1].\n"
" *\n"
" * renderCoord:  em-space sample position (interpolated from vertex shader)\n"
" * glyphLoc:     offset into hb_gpu_atlas for this glyph's encoded blob\n"
" * hb_gpu_atlas: storage buffer with the glyph atlas data\n"
" */\n"
"fn hb_gpu_render (renderCoord: vec2f, glyphLoc_: u32,\n"
"                  hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>) -> f32\n"
"{\n"
"  let emsPerPixel = fwidth (renderCoord);\n"
"  let pixelsPerEm = 1.0 / emsPerPixel;\n"
"\n"
"  let glyphLoc = i32 (glyphLoc_);\n"
"\n"
"  /* Read blob header */\n"
"  let header0 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc);\n"
"  let header1 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + 1);\n"
"  let ext = vec4f (header0) * HB_GPU_INV_UNITS; /* min_x, min_y, max_x, max_y */\n"
"  let numHBands = header1.r;\n"
"  let numVBands = header1.g;\n"
"\n"
"  /* Compute band transform from extents */\n"
"  let extSize = ext.zw - ext.xy; /* (width, height) */\n"
"  let bandScale = vec2f (f32 (numVBands), f32 (numHBands)) / max (extSize, vec2f (1.0 / 65536.0));\n"
"  let bandOffset = -ext.xy * bandScale;\n"
"\n"
"  let bandIndex = clamp (vec2<i32> (renderCoord * bandScale + bandOffset),\n"
"                         vec2<i32> (0, 0),\n"
"                         vec2<i32> (numVBands - 1, numHBands - 1));\n"
"\n"
"  /* Skip past header (2 texels) */\n"
"  let bandBase = glyphLoc + 2;\n"
"\n"
"  var xcov: f32 = 0.0;\n"
"  var xwgt: f32 = 0.0;\n"
"\n"
"  let hbandData = _hb_gpu_fetch (hb_gpu_atlas, bandBase + bandIndex.y);\n"
"  let hCurveCount = hbandData.r;\n"
"  /* Symmetric: choose rightward (desc) or leftward (asc) sort */\n"
"  let hSplit = f32 (hbandData.a) * HB_GPU_INV_UNITS;\n"
"  let hLeftRay = (renderCoord.x < hSplit);\n"
"  var hDataOffset: i32;\n"
"  if (hLeftRay) { hDataOffset = hbandData.b + 32768; }\n"
"  else          { hDataOffset = hbandData.g + 32768; }\n"
"\n"
"  for (var ci: i32 = 0; ci < hCurveCount; ci++)\n"
"  {\n"
"    let curveOffset = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + hDataOffset + ci).r + 32768;\n"
"\n"
"    let raw12 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset);\n"
"    let raw3 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset + 1);\n"
"\n"
"    let q12 = vec4f (raw12) * HB_GPU_INV_UNITS;\n"
"    let q3 = vec2f (vec2<i32> (raw3.r, raw3.g)) * HB_GPU_INV_UNITS;\n"
"\n"
"    let p12 = q12 - vec4f (renderCoord, renderCoord);\n"
"    let p3 = q3 - renderCoord;\n"
"\n"
"    if (hLeftRay) {\n"
"      if (min (min (p12.x, p12.z), p3.x) * pixelsPerEm.x > 0.5) { break; }\n"
"    } else {\n"
"      if (max (max (p12.x, p12.z), p3.x) * pixelsPerEm.x < -0.5) { break; }\n"
"    }\n"
"\n"
"    let code = _hb_gpu_calc_root_code (p12.y, p12.w, p3.y);\n"
"    if (code != 0u)\n"
"    {\n"
"      let a = q12.xy - q12.zw * 2.0 + q3;\n"
"      let b = q12.xy - q12.zw;\n"
"      let r = _hb_gpu_solve_horiz_poly (a, b, p12.xy) * pixelsPerEm.x;\n"
"      /* For leftward ray: saturate(0.5 - r) counts coverage from the left */\n"
"      var cov: vec2f;\n"
"      if (hLeftRay) { cov = clamp (vec2f (0.5) - r, vec2f (0.0), vec2f (1.0)); }\n"
"      else          { cov = clamp (r + vec2f (0.5), vec2f (0.0), vec2f (1.0)); }\n"
"\n"
"      if ((code & 1u) != 0u)\n"
"      {\n"
"        xcov += cov.x;\n"
"        xwgt = max (xwgt, clamp (1.0 - abs (r.x) * 2.0, 0.0, 1.0));\n"
"      }\n"
"\n"
"      if (code > 1u)\n"
"      {\n"
"        xcov -= cov.y;\n"
"        xwgt = max (xwgt, clamp (1.0 - abs (r.y) * 2.0, 0.0, 1.0));\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  var ycov: f32 = 0.0;\n"
"  var ywgt: f32 = 0.0;\n"
"\n"
"  let vbandData = _hb_gpu_fetch (hb_gpu_atlas, bandBase + numHBands + bandIndex.x);\n"
"  let vCurveCount = vbandData.r;\n"
"  let vSplit = f32 (vbandData.a) * HB_GPU_INV_UNITS;\n"
"  let vLeftRay = (renderCoord.y < vSplit);\n"
"  var vDataOffset: i32;\n"
"  if (vLeftRay) { vDataOffset = vbandData.b + 32768; }\n"
"  else          { vDataOffset = vbandData.g + 32768; }\n"
"\n"
"  for (var ci: i32 = 0; ci < vCurveCount; ci++)\n"
"  {\n"
"    let curveOffset = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + vDataOffset + ci).r + 32768;\n"
"\n"
"    let raw12 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset);\n"
"    let raw3 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset + 1);\n"
"\n"
"    let q12 = vec4f (raw12) * HB_GPU_INV_UNITS;\n"
"    let q3 = vec2f (vec2<i32> (raw3.r, raw3.g)) * HB_GPU_INV_UNITS;\n"
"\n"
"    let p12 = q12 - vec4f (renderCoord, renderCoord);\n"
"    let p3 = q3 - renderCoord;\n"
"\n"
"    if (vLeftRay) {\n"
"      if (min (min (p12.y, p12.w), p3.y) * pixelsPerEm.y > 0.5) { break; }\n"
"    } else {\n"
"      if (max (max (p12.y, p12.w), p3.y) * pixelsPerEm.y < -0.5) { break; }\n"
"    }\n"
"\n"
"    let code = _hb_gpu_calc_root_code (p12.x, p12.z, p3.x);\n"
"    if (code != 0u)\n"
"    {\n"
"      let a = q12.xy - q12.zw * 2.0 + q3;\n"
"      let b = q12.xy - q12.zw;\n"
"      let r = _hb_gpu_solve_vert_poly (a, b, p12.xy) * pixelsPerEm.y;\n"
"      var cov: vec2f;\n"
"      if (vLeftRay) { cov = clamp (vec2f (0.5) - r, vec2f (0.0), vec2f (1.0)); }\n"
"      else          { cov = clamp (r + vec2f (0.5), vec2f (0.0), vec2f (1.0)); }\n"
"\n"
"      if ((code & 1u) != 0u)\n"
"      {\n"
"        ycov -= cov.x;\n"
"        ywgt = max (ywgt, clamp (1.0 - abs (r.x) * 2.0, 0.0, 1.0));\n"
"      }\n"
"\n"
"      if (code > 1u)\n"
"      {\n"
"        ycov += cov.y;\n"
"        ywgt = max (ywgt, clamp (1.0 - abs (r.y) * 2.0, 0.0, 1.0));\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  return _hb_gpu_calc_coverage (xcov, ycov, xwgt, ywgt);\n"
"}\n"
;
