static const char *hb_gpu_paint_fragment_wgsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Paint-renderer fragment shader (WGSL).\n"
" *\n"
" * Assumes the shared fragment helpers (hb-gpu-fragment.wgsl) and\n"
" * the draw-renderer fragment helpers (hb-gpu-draw-fragment.wgsl)\n"
" * are prepended to this source.\n"
" *\n"
" * atlas is passed as an explicit storage-buffer pointer parameter,\n"
" * matching WGSL's scoping rules.\n"
" */\n"
"\n"
"\n"
"fn _hb_gpu_stop_color (hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>,\n"
"                       stops_base: i32, i: i32, foreground: vec4f,\n"
"                       offset: ptr<function, f32>) -> vec4f\n"
"{\n"
"  let a = hb_gpu_fetch (hb_gpu_atlas, stops_base + i * 2);\n"
"  *offset = f32 (a.r) / 32767.0;\n"
"  if ((a.g & 1) != 0) {\n"
"    return foreground;\n"
"  }\n"
"  let b = hb_gpu_fetch (hb_gpu_atlas, stops_base + i * 2 + 1);\n"
"  return vec4f (b) / 32767.0;\n"
"}\n"
"\n"
"fn _hb_gpu_extend_t (t: f32, extend: i32) -> f32\n"
"{\n"
"  if (extend == 1) { return t - floor (t); }\n"
"  if (extend == 2) {\n"
"    let u = t - 2.0 * floor (t * 0.5);\n"
"    if (u > 1.0) { return 2.0 - u; }\n"
"    return u;\n"
"  }\n"
"  return clamp (t, 0.0, 1.0);\n"
"}\n"
"\n"
"fn _hb_gpu_eval_stops (hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>,\n"
"                       stops_base: i32, stop_count: i32,\n"
"                       t: f32, foreground: vec4f) -> vec4f\n"
"{\n"
"  var off_prev: f32;\n"
"  var col_prev = _hb_gpu_stop_color (hb_gpu_atlas, stops_base, 0, foreground, &off_prev);\n"
"  if (t <= off_prev) { return col_prev; }\n"
"  for (var i: i32 = 1; i < stop_count; i = i + 1)\n"
"  {\n"
"    var off: f32;\n"
"    let col = _hb_gpu_stop_color (hb_gpu_atlas, stops_base, i, foreground, &off);\n"
"    if (t <= off)\n"
"    {\n"
"      let span = off - off_prev;\n"
"      var f: f32 = 0.0;\n"
"      if (span > 1e-6) { f = (t - off_prev) / span; }\n"
"      return mix (col_prev, col, f);\n"
"    }\n"
"    col_prev = col;\n"
"    off_prev = off;\n"
"  }\n"
"  return col_prev;\n"
"}\n"
"\n"
"fn _hb_gpu_sample_linear (renderCoord: vec2f, grad_base: i32,\n"
"                          stop_count: i32, extend: i32, foreground: vec4f,\n"
"                          hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>) -> vec4f\n"
"{\n"
"  let axis = hb_gpu_fetch (hb_gpu_atlas, grad_base);\n"
"  let p0 = vec2f (f32 (axis.r), f32 (axis.g));\n"
"  let p1 = vec2f (f32 (axis.b), f32 (axis.a));\n"
"  let d = p1 - p0;\n"
"  let denom = dot (d, d);\n"
"  if (denom < 1e-6) { return vec4f (0.0); }\n"
"  var t = dot (renderCoord - p0, d) / denom;\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (hb_gpu_atlas, grad_base + 1, stop_count, t, foreground);\n"
"}\n"
"\n"
"fn _hb_gpu_sample_radial (renderCoord: vec2f, grad_base: i32,\n"
"                          stop_count: i32, extend: i32, foreground: vec4f,\n"
"                          hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>) -> vec4f\n"
"{\n"
"  let c0_ = hb_gpu_fetch (hb_gpu_atlas, grad_base);\n"
"  let c1_ = hb_gpu_fetch (hb_gpu_atlas, grad_base + 1);\n"
"  let c0 = vec2f (f32 (c0_.r), f32 (c0_.g));\n"
"  let r0 = f32 (c0_.b);\n"
"  let c1 = vec2f (f32 (c1_.r), f32 (c1_.g));\n"
"  let r1 = f32 (c1_.b);\n"
"\n"
"  let cd = c1 - c0;\n"
"  let dr = r1 - r0;\n"
"  let p  = renderCoord - c0;\n"
"\n"
"  let A = dot (cd, cd) - dr * dr;\n"
"  let B = -2.0 * (dot (p, cd) + r0 * dr);\n"
"  let C = dot (p, p) - r0 * r0;\n"
"\n"
"  var t: f32;\n"
"  if (abs (A) > 1e-6)\n"
"  {\n"
"    let disc = B * B - 4.0 * A * C;\n"
"    if (disc < 0.0) { return vec4f (0.0); }\n"
"    let sq = sqrt (disc);\n"
"    let t1 = (-B + sq) / (2.0 * A);\n"
"    let t2 = (-B - sq) / (2.0 * A);\n"
"    if (r0 + t1 * dr >= 0.0) { t = t1; } else { t = t2; }\n"
"  }\n"
"  else\n"
"  {\n"
"    if (abs (B) < 1e-6) { return vec4f (0.0); }\n"
"    t = -C / B;\n"
"  }\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (hb_gpu_atlas, grad_base + 2, stop_count, t, foreground);\n"
"}\n"
"\n"
"fn _hb_gpu_sample_sweep (renderCoord: vec2f, grad_base: i32,\n"
"                         stop_count: i32, extend: i32, foreground: vec4f,\n"
"                         hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>) -> vec4f\n"
"{\n"
"  let t0 = hb_gpu_fetch (hb_gpu_atlas, grad_base);\n"
"  let c = vec2f (f32 (t0.r), f32 (t0.g));\n"
"  let a0 = f32 (t0.b) / 16384.0;\n"
"  let a1 = f32 (t0.a) / 16384.0;\n"
"  let span = a1 - a0;\n"
"  if (abs (span) < 1e-6) { return vec4f (0.0); }\n"
"\n"
"  let p = renderCoord - c;\n"
"  var ang = atan2 (p.y, p.x) / 3.14159265358979;\n"
"  if (ang < 0.0) { ang = ang + 2.0; }\n"
"  var t = (ang - a0) / span;\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (hb_gpu_atlas, grad_base + 1, stop_count, t, foreground);\n"
"}\n"
"\n"
"fn hb_gpu_paint (renderCoord: vec2f, glyphLoc_: u32, foreground: vec4f,\n"
"                 hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>) -> vec4f\n"
"{\n"
"  /* Compute pixelsPerEm once here at uniform control flow.  WGSL\n"
"   * rejects fwidth inside a loop-conditional branch, so we call\n"
"   * _hb_gpu_draw_impl (the MSAA-aware implementation that takes a\n"
"   * pre-computed pixelsPerEm) instead of the top-level\n"
"   * hb_gpu_draw() which would re-call fwidth. */\n"
"  let emsPerPixel = fwidth (renderCoord);\n"
"  let pixelsPerEm = 1.0 / emsPerPixel;\n"
"\n"
"  let base    = i32 (glyphLoc_);\n"
"  let h0      = hb_gpu_fetch (hb_gpu_atlas, base);     // (num_ops, _, _, _)\n"
"  let h2      = hb_gpu_fetch (hb_gpu_atlas, base + 2); // (ops_offset, _, _, _)\n"
"  let num_ops = h0.r;\n"
"  var cursor  = base + h2.r;\n"
"\n"
"  var acc = vec4f (0.0);\n"
"\n"
"  for (var i: i32 = 0; i < num_ops; i = i + 1)\n"
"  {\n"
"    let op      = hb_gpu_fetch (hb_gpu_atlas, cursor);\n"
"    let op_type = op.r;\n"
"    let aux     = op.g;\n"
"    let payload = (op.b << 16) | (op.a & 0xffff);\n"
"\n"
"    if (op_type == 0) {  // LAYER_SOLID\n"
"      // texel 1 holds RGBA as signed Q15.\n"
"      let ct = hb_gpu_fetch (hb_gpu_atlas, cursor + 1);\n"
"      var col: vec4f;\n"
"      if ((aux & 1) != 0) {\n"
"        col = foreground;\n"
"      } else {\n"
"        col = vec4f (ct) / 32767.0;\n"
"      }\n"
"\n"
"      let cov = _hb_gpu_draw_impl (renderCoord, pixelsPerEm,\n"
"                                   u32 (base + payload), hb_gpu_atlas);\n"
"      let src = vec4f (col.rgb * col.a, col.a) * cov;\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor = cursor + 2;\n"
"    } else if (op_type == 1) {  // LAYER_GRADIENT\n"
"      let op2 = hb_gpu_fetch (hb_gpu_atlas, cursor + 1);\n"
"      let grad_payload = (op2.r << 16) | (op2.g & 0xffff);\n"
"      let extend = op2.b;\n"
"      let stop_count = op2.a;\n"
"\n"
"      var col = vec4f (0.0);\n"
"      if (aux == 0) {\n"
"        col = _hb_gpu_sample_linear (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground,\n"
"                                     hb_gpu_atlas);\n"
"      } else if (aux == 1) {\n"
"        col = _hb_gpu_sample_radial (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground,\n"
"                                     hb_gpu_atlas);\n"
"      } else if (aux == 2) {\n"
"        col = _hb_gpu_sample_sweep  (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground,\n"
"                                     hb_gpu_atlas);\n"
"      }\n"
"\n"
"      let cov = _hb_gpu_draw_impl (renderCoord, pixelsPerEm,\n"
"                                   u32 (base + payload), hb_gpu_atlas);\n"
"      let src = vec4f (col.rgb * col.a, col.a) * cov;\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor = cursor + 2;\n"
"    } else {\n"
"      /* PUSH_GROUP, POP_GROUP not yet handled. */\n"
"      break;\n"
"    }\n"
"  }\n"
"\n"
"  return acc;\n"
"}\n"
;
