static const char *hb_gpu_paint_fragment_wgsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Paint-renderer fragment shader (WGSL).\n"
" *\n"
" * Assumes the shared fragment helpers (hb-gpu-fragment.wgsl) and\n"
" * the draw-renderer fragment helpers (hb-gpu-draw-fragment.wgsl)\n"
" * are prepended to this source.\n"
" *\n"
" * atlas and palette are passed as explicit storage-buffer pointer\n"
" * parameters, matching WGSL's scoping rules.\n"
" */\n"
"\n"
"\n"
"fn hb_gpu_paint (renderCoord: vec2f, glyphLoc_: u32, foreground: vec4f,\n"
"                 hb_gpu_atlas: ptr<storage, array<vec4<i32>>, read>,\n"
"                 hb_gpu_palette: ptr<storage, array<vec4f>, read>) -> vec4f\n"
"{\n"
"  let base    = i32 (glyphLoc_);\n"
"  let h0      = hb_gpu_fetch (hb_gpu_atlas, base);     // (num_ops, _, _, _)\n"
"  let h2      = hb_gpu_fetch (hb_gpu_atlas, base + 2); // (ops_offset, _, _, _)\n"
"  let num_ops = h0.r;\n"
"  var cursor  = base + h2.r;\n"
"\n"
"  var acc = vec4f (0.0);\n"
"\n"
"  for (var i: i32 = 0; i < num_ops; i = i + 1)\n"
"  {\n"
"    let op      = hb_gpu_fetch (hb_gpu_atlas, cursor);\n"
"    let op_type = op.r;\n"
"    let payload = (op.b << 16) | (op.a & 0xffff);\n"
"\n"
"    if (op_type == 0) {  // LAYER_SOLID\n"
"      let ct = hb_gpu_fetch (hb_gpu_atlas, cursor + 1);\n"
"      let palette_index = ct.r;\n"
"      let flags         = ct.g;\n"
"      let alpha         = f32 (ct.b) / 32767.0;\n"
"\n"
"      var col: vec4f;\n"
"      if ((flags & 1) != 0) {\n"
"        col = foreground;\n"
"      } else {\n"
"        col = (*hb_gpu_palette)[palette_index];\n"
"      }\n"
"      col.a = col.a * alpha;\n"
"\n"
"      let cov = hb_gpu_draw (renderCoord, u32 (base + payload), hb_gpu_atlas);\n"
"      let src = col * cov;\n"
"      /* SRC_OVER with premultiplied source. */\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor = cursor + 2;\n"
"    } else {\n"
"      /* LAYER_GRADIENT, PUSH_GROUP, POP_GROUP not yet handled. */\n"
"      break;\n"
"    }\n"
"  }\n"
"\n"
"  return acc;\n"
"}\n"
;
