static const char *hb_gpu_paint_fragment_hlsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Paint-renderer fragment shader (HLSL).\n"
" *\n"
" * Assumes the shared fragment helpers (hb-gpu-fragment.hlsl) and\n"
" * the draw-renderer fragment helpers (hb-gpu-draw-fragment.hlsl)\n"
" * are prepended to this source.\n"
" */\n"
"\n"
"\n"
"float4 hb_gpu_paint (float2 renderCoord, uint glyphLoc_, float4 foreground)\n"
"{\n"
"  /* fwidth once, at uniform control flow. */\n"
"  float2 pixelsPerEm = 1.0 / fwidth (renderCoord);\n"
"\n"
"  int base    = (int) glyphLoc_;\n"
"  int4 h0     = hb_gpu_fetch (base);       /* (num_ops, _, _, _) */\n"
"  int4 h2     = hb_gpu_fetch (base + 2);   /* (ops_offset, _, _, _) */\n"
"  int num_ops = h0.r;\n"
"  int cursor  = base + h2.r;\n"
"\n"
"  float4 acc = float4 (0.0, 0.0, 0.0, 0.0);\n"
"\n"
"  for (int i = 0; i < num_ops; i++)\n"
"  {\n"
"    int4 op     = hb_gpu_fetch (cursor);\n"
"    int op_type = op.r;\n"
"    int flags   = op.g;\n"
"    int payload = (op.b << 16) | (op.a & 0xffff);\n"
"\n"
"    if (op_type == 0)  /* LAYER_SOLID */\n"
"    {\n"
"      /* texel 1 holds RGBA as signed Q15. */\n"
"      int4 ct = hb_gpu_fetch (cursor + 1);\n"
"      float4 col = ((flags & 1) != 0)\n"
"		 ? foreground\n"
"		 : (float4) ct / 32767.0;\n"
"\n"
"      float cov = _hb_gpu_draw_impl (renderCoord, pixelsPerEm,\n"
"				     (uint) (base + payload));\n"
"      float4 src = col * cov;\n"
"      /* SRC_OVER with premultiplied source. */\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor += 2;\n"
"    }\n"
"    else\n"
"    {\n"
"      /* LAYER_GRADIENT, PUSH_GROUP, POP_GROUP not yet handled. */\n"
"      break;\n"
"    }\n"
"  }\n"
"\n"
"  return acc;\n"
"}\n"
;
