static const char *hb_gpu_paint_fragment_glsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Paint-renderer fragment shader.\n"
" *\n"
" * Assumes the shared fragment helpers (hb-gpu-fragment.glsl) and\n"
" * the draw-renderer fragment helpers (hb-gpu-draw-fragment.glsl)\n"
" * are prepended to this source.  The draw helper provides\n"
" * hb_gpu_draw() which this interpreter calls to compute clip-glyph\n"
" * coverage.\n"
" */\n"
"\n"
"\n"
"/* Fetch the i'th stop of a gradient color line starting at @stops_base\n"
" * (2 texels per stop).  Resolves is_foreground to @foreground. */\n"
"vec4 _hb_gpu_stop_color (int stops_base, int i, vec4 foreground, out float offset)\n"
"{\n"
"  ivec4 a = hb_gpu_fetch (stops_base + i * 2);\n"
"  offset = float (a.r) / 32767.0;\n"
"  if ((a.g & 1) != 0)\n"
"    return foreground;\n"
"  ivec4 b = hb_gpu_fetch (stops_base + i * 2 + 1);\n"
"  return vec4 (b) / 32767.0;\n"
"}\n"
"\n"
"/* Apply the color-line extend mode to a projected `t` value. */\n"
"float _hb_gpu_extend_t (float t, int extend)\n"
"{\n"
"  if (extend == 1) {           /* HB_PAINT_EXTEND_REPEAT */\n"
"    return t - floor (t);\n"
"  } else if (extend == 2) {    /* HB_PAINT_EXTEND_REFLECT */\n"
"    float u = t - 2.0 * floor (t * 0.5);\n"
"    return u > 1.0 ? 2.0 - u : u;\n"
"  }\n"
"  return clamp (t, 0.0, 1.0);  /* PAD (default) */\n"
"}\n"
"\n"
"/* Walk stops starting at @stops_base and return the sampled color\n"
" * at @t.  Same logic reused by all gradient subtypes. */\n"
"vec4 _hb_gpu_eval_stops (int stops_base, int stop_count, float t, vec4 foreground)\n"
"{\n"
"  float off_prev;\n"
"  vec4 col_prev = _hb_gpu_stop_color (stops_base, 0, foreground, off_prev);\n"
"  if (t <= off_prev)\n"
"    return col_prev;\n"
"  for (int i = 1; i < stop_count; i++)\n"
"  {\n"
"    float off;\n"
"    vec4 col = _hb_gpu_stop_color (stops_base, i, foreground, off);\n"
"    if (t <= off)\n"
"    {\n"
"      float span = off - off_prev;\n"
"      float f = span > 1e-6 ? (t - off_prev) / span : 0.0;\n"
"      return mix (col_prev, col, f);\n"
"    }\n"
"    col_prev = col;\n"
"    off_prev = off;\n"
"  }\n"
"  return col_prev;\n"
"}\n"
"\n"
"/* Sample a linear gradient whose param blob starts at @grad_base:\n"
" *   texel 0: (x0, y0, x1, y1) in font units (i16)\n"
" *   texels 1..: stops (2 texels each) */\n"
"vec4 _hb_gpu_sample_linear (vec2 renderCoord, int grad_base,\n"
"			    int stop_count, int extend, vec4 foreground)\n"
"{\n"
"  ivec4 axis = hb_gpu_fetch (grad_base);\n"
"  vec2 p0 = vec2 (float (axis.r), float (axis.g));\n"
"  vec2 p1 = vec2 (float (axis.b), float (axis.a));\n"
"  vec2 d = p1 - p0;\n"
"  float denom = dot (d, d);\n"
"  if (denom < 1e-6) return vec4 (0.0);\n"
"  float t = dot (renderCoord - p0, d) / denom;\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"\n"
"  return _hb_gpu_eval_stops (grad_base + 1, stop_count, t, foreground);\n"
"}\n"
"\n"
"/* Sample a two-circle radial gradient whose param blob starts at\n"
" * @grad_base:\n"
" *   texel 0: (x0, y0, r0, _)\n"
" *   texel 1: (x1, y1, r1, _)\n"
" *   texels 2..: stops (2 texels each)\n"
" * Solves |P - C0 - t*(C1-C0)|^2 = (r0 + t*(r1-r0))^2 for t. */\n"
"vec4 _hb_gpu_sample_radial (vec2 renderCoord, int grad_base,\n"
"			    int stop_count, int extend, vec4 foreground)\n"
"{\n"
"  ivec4 c0_ = hb_gpu_fetch (grad_base);\n"
"  ivec4 c1_ = hb_gpu_fetch (grad_base + 1);\n"
"  vec2 c0 = vec2 (float (c0_.r), float (c0_.g));\n"
"  float r0 = float (c0_.b);\n"
"  vec2 c1 = vec2 (float (c1_.r), float (c1_.g));\n"
"  float r1 = float (c1_.b);\n"
"\n"
"  vec2 cd = c1 - c0;\n"
"  float dr = r1 - r0;\n"
"  vec2 p  = renderCoord - c0;\n"
"\n"
"  float A = dot (cd, cd) - dr * dr;\n"
"  float B = -2.0 * (dot (p, cd) + r0 * dr);\n"
"  float C = dot (p, p) - r0 * r0;\n"
"\n"
"  float t;\n"
"  if (abs (A) > 1e-6)\n"
"  {\n"
"    float disc = B * B - 4.0 * A * C;\n"
"    if (disc < 0.0) return vec4 (0.0);\n"
"    float sq = sqrt (disc);\n"
"    /* Prefer the larger root; fall back to the smaller if the\n"
"     * larger gives a negative interpolated radius. */\n"
"    float t1 = (-B + sq) / (2.0 * A);\n"
"    float t2 = (-B - sq) / (2.0 * A);\n"
"    t = (r0 + t1 * dr >= 0.0) ? t1 : t2;\n"
"  }\n"
"  else\n"
"  {\n"
"    if (abs (B) < 1e-6) return vec4 (0.0);\n"
"    t = -C / B;\n"
"  }\n"
"\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (grad_base + 2, stop_count, t, foreground);\n"
"}\n"
"\n"
"/* Sample a sweep gradient whose param blob starts at @grad_base:\n"
" *   texel 0: (cx, cy, start_q14, end_q14)\n"
" *            start/end are Q14 fractions of pi\n"
" *   texels 1..: stops (2 texels each) */\n"
"vec4 _hb_gpu_sample_sweep (vec2 renderCoord, int grad_base,\n"
"			   int stop_count, int extend, vec4 foreground)\n"
"{\n"
"  ivec4 t0 = hb_gpu_fetch (grad_base);\n"
"  vec2 c = vec2 (float (t0.r), float (t0.g));\n"
"  float a0 = float (t0.b) / 16384.0;  /* fraction of pi */\n"
"  float a1 = float (t0.a) / 16384.0;\n"
"  float span = a1 - a0;\n"
"  if (abs (span) < 1e-6) return vec4 (0.0);\n"
"\n"
"  vec2 p = renderCoord - c;\n"
"  /* atan2 returns (-pi, pi]; normalize to [0, 2) fractions of pi. */\n"
"  float ang = atan (p.y, p.x) / 3.14159265358979;\n"
"  if (ang < 0.0) ang += 2.0;\n"
"  float t = (ang - a0) / span;\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (grad_base + 1, stop_count, t, foreground);\n"
"}\n"
"\n"
"/* Composite two premultiplied RGBA layers using one of the COLRv1\n"
" * compositing modes.  Unsupported modes fall back to SRC_OVER.\n"
" * Values match hb_paint_composite_mode_t. */\n"
"vec4 _hb_gpu_composite (vec4 src, vec4 dst, int mode)\n"
"{\n"
"  vec4 r = src + dst * (1.0 - src.a);  /* SRC_OVER default */\n"
"\n"
"  if      (mode == 0)  r = vec4 (0.0);                       /* CLEAR */\n"
"  else if (mode == 1)  r = src;                              /* SRC */\n"
"  else if (mode == 2)  r = dst;                              /* DST */\n"
"  else if (mode == 4)  r = dst + src * (1.0 - dst.a);        /* DST_OVER */\n"
"  else if (mode == 5)  r = src * dst.a;                      /* SRC_IN */\n"
"  else if (mode == 6)  r = dst * src.a;                      /* DST_IN */\n"
"  else if (mode == 7)  r = src * (1.0 - dst.a);              /* SRC_OUT */\n"
"  else if (mode == 8)  r = dst * (1.0 - src.a);              /* DST_OUT */\n"
"  else if (mode == 9)                                        /* SRC_ATOP */\n"
"    r = src * dst.a + dst * (1.0 - src.a);\n"
"  else if (mode == 10)                                       /* DST_ATOP */\n"
"    r = dst * src.a + src * (1.0 - dst.a);\n"
"  else if (mode == 11)                                       /* XOR */\n"
"    r = src * (1.0 - dst.a) + dst * (1.0 - src.a);\n"
"  else if (mode == 12)                                       /* PLUS */\n"
"    r = min (src + dst, vec4 (1.0));\n"
"  else if (mode == 13) {                                     /* SCREEN (premul) */\n"
"    r.rgb = src.rgb + dst.rgb - src.rgb * dst.rgb;\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  else if (mode == 15) {                                     /* DARKEN */\n"
"    r.rgb = min (src.rgb * dst.a, dst.rgb * src.a)\n"
"          + src.rgb * (1.0 - dst.a) + dst.rgb * (1.0 - src.a);\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  else if (mode == 16) {                                     /* LIGHTEN */\n"
"    r.rgb = max (src.rgb * dst.a, dst.rgb * src.a)\n"
"          + src.rgb * (1.0 - dst.a) + dst.rgb * (1.0 - src.a);\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  else if (mode == 23) {                                     /* MULTIPLY (premul) */\n"
"    r.rgb = src.rgb * (1.0 - dst.a) + dst.rgb * (1.0 - src.a)\n"
"          + src.rgb * dst.rgb;\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  /* SRC_OVER (3) and any unsupported mode use the default `r`. */\n"
"\n"
"  return r;\n"
"}\n"
"\n"
"/* Walks the paint blob's flat op stream and returns a\n"
" * premultiplied RGBA coverage value for the current fragment.\n"
" *\n"
" * glyphLoc: atlas texel offset of the paint-blob header.\n"
" * foreground: caller-supplied foreground color, used when an op\n"
" *             sets the is_foreground flag.\n"
" */\n"
"#define HB_GPU_PAINT_GROUP_DEPTH 4\n"
"\n"
"vec4 hb_gpu_paint (vec2 renderCoord, uint glyphLoc, vec4 foreground)\n"
"{\n"
"  /* fwidth once, at uniform control flow: every per-layer\n"
"   * coverage sample below uses this pre-computed pixelsPerEm via\n"
"   * _hb_gpu_draw_impl. */\n"
"  vec2 pixelsPerEm = 1.0 / fwidth (renderCoord);\n"
"\n"
"  int base    = int (glyphLoc);\n"
"  ivec4 h0    = hb_gpu_fetch (base);      /* (num_ops, _, _, _) */\n"
"  ivec4 h2    = hb_gpu_fetch (base + 2);  /* (ops_offset, _, _, _) */\n"
"  int num_ops = h0.r;\n"
"  int cursor  = base + h2.r;\n"
"\n"
"  vec4 acc = vec4 (0.0);\n"
"  vec4 group_stack[HB_GPU_PAINT_GROUP_DEPTH];\n"
"  int sp = 0;\n"
"\n"
"  for (int i = 0; i < num_ops; i++)\n"
"  {\n"
"    ivec4 op    = hb_gpu_fetch (cursor);\n"
"    int op_type = op.r;\n"
"    int aux     = op.g;\n"
"    int payload = (op.b << 16) | (op.a & 0xffff);\n"
"\n"
"    if (op_type == 0)  /* LAYER_SOLID */\n"
"    {\n"
"      /* texel 1 holds RGBA as signed Q15. */\n"
"      ivec4 ct = hb_gpu_fetch (cursor + 1);\n"
"      vec4 col = ((aux & 1) != 0)\n"
"	       ? foreground\n"
"	       : vec4 (ct) / 32767.0;\n"
"\n"
"      float cov = _hb_gpu_draw_impl (renderCoord, pixelsPerEm,\n"
"				     uint (base + payload));\n"
"      vec4 src = vec4 (col.rgb * col.a, col.a) * cov;\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor += 2;\n"
"    }\n"
"    else if (op_type == 1)  /* LAYER_GRADIENT */\n"
"    {\n"
"      /* texel 1: (grad_payload_hi, grad_payload_lo, extend, stop_count) */\n"
"      ivec4 op2 = hb_gpu_fetch (cursor + 1);\n"
"      int grad_payload = (op2.r << 16) | (op2.g & 0xffff);\n"
"      int extend       = op2.b;\n"
"      int stop_count   = op2.a;\n"
"\n"
"      vec4 col = vec4 (0.0);\n"
"      if (aux == 0)       /* linear */\n"
"        col = _hb_gpu_sample_linear (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground);\n"
"      else if (aux == 1)  /* radial */\n"
"        col = _hb_gpu_sample_radial (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground);\n"
"      else if (aux == 2)  /* sweep */\n"
"        col = _hb_gpu_sample_sweep  (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground);\n"
"\n"
"      float cov = _hb_gpu_draw_impl (renderCoord, pixelsPerEm,\n"
"				     uint (base + payload));\n"
"      vec4 src = vec4 (col.rgb * col.a, col.a) * cov;\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor += 2;\n"
"    }\n"
"    else if (op_type == 2)  /* PUSH_GROUP */\n"
"    {\n"
"      if (sp < HB_GPU_PAINT_GROUP_DEPTH) {\n"
"        group_stack[sp] = acc;\n"
"        sp++;\n"
"      }\n"
"      acc = vec4 (0.0);\n"
"      cursor += 1;\n"
"    }\n"
"    else if (op_type == 3)  /* POP_GROUP */\n"
"    {\n"
"      if (sp > 0) {\n"
"        sp--;\n"
"        vec4 src = acc;\n"
"        vec4 dst = group_stack[sp];\n"
"        acc = _hb_gpu_composite (src, dst, aux);\n"
"      }\n"
"      cursor += 1;\n"
"    }\n"
"    else\n"
"    {\n"
"      break;\n"
"    }\n"
"  }\n"
"\n"
"  return acc;\n"
"}\n"
;
