static const char *hb_gpu_paint_fragment_msl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Paint-renderer fragment shader (Metal).\n"
" *\n"
" * Assumes the shared fragment helpers (hb-gpu-fragment.msl) and\n"
" * the draw-renderer fragment helpers (hb-gpu-draw-fragment.msl)\n"
" * are prepended to this source.\n"
" */\n"
"\n"
"\n"
"/* Fetch the i'th stop (2 texels per stop), resolving is_foreground. */\n"
"static float4 _hb_gpu_stop_color (device const short4* hb_gpu_atlas,\n"
"				  int stops_base, int i, float4 foreground,\n"
"				  thread float &offset)\n"
"{\n"
"  int4 a = int4 (hb_gpu_atlas[stops_base + i * 2]);\n"
"  offset = float (a.r) / 32767.0;\n"
"  if ((a.g & 1) != 0)\n"
"    return foreground;\n"
"  int4 b = int4 (hb_gpu_atlas[stops_base + i * 2 + 1]);\n"
"  return float4 (b) / 32767.0;\n"
"}\n"
"\n"
"static float _hb_gpu_extend_t (float t, int extend)\n"
"{\n"
"  if (extend == 1) return t - floor (t);\n"
"  if (extend == 2) {\n"
"    float u = t - 2.0 * floor (t * 0.5);\n"
"    return u > 1.0 ? 2.0 - u : u;\n"
"  }\n"
"  return clamp (t, 0.0, 1.0);\n"
"}\n"
"\n"
"static float4 _hb_gpu_eval_stops (device const short4* hb_gpu_atlas,\n"
"				  int stops_base, int stop_count,\n"
"				  float t, float4 foreground)\n"
"{\n"
"  float off_prev;\n"
"  float4 col_prev = _hb_gpu_stop_color (hb_gpu_atlas, stops_base, 0, foreground, off_prev);\n"
"  if (t <= off_prev) return col_prev;\n"
"  for (int i = 1; i < stop_count; i++)\n"
"  {\n"
"    float off;\n"
"    float4 col = _hb_gpu_stop_color (hb_gpu_atlas, stops_base, i, foreground, off);\n"
"    if (t <= off)\n"
"    {\n"
"      float span = off - off_prev;\n"
"      float f = span > 1e-6 ? (t - off_prev) / span : 0.0;\n"
"      return mix (col_prev, col, f);\n"
"    }\n"
"    col_prev = col;\n"
"    off_prev = off;\n"
"  }\n"
"  return col_prev;\n"
"}\n"
"\n"
"static float4 _hb_gpu_sample_linear (float2 renderCoord, int grad_base,\n"
"				     int stop_count, int extend,\n"
"				     float4 foreground,\n"
"				     device const short4* hb_gpu_atlas)\n"
"{\n"
"  int4 axis = int4 (hb_gpu_atlas[grad_base]);\n"
"  float2 p0 = float2 (float (axis.r), float (axis.g));\n"
"  float2 p1 = float2 (float (axis.b), float (axis.a));\n"
"  float2 d = p1 - p0;\n"
"  float denom = dot (d, d);\n"
"  if (denom < 1e-6) return float4 (0.0);\n"
"  float t = dot (renderCoord - p0, d) / denom;\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (hb_gpu_atlas, grad_base + 1, stop_count, t, foreground);\n"
"}\n"
"\n"
"static float4 _hb_gpu_sample_radial (float2 renderCoord, int grad_base,\n"
"				     int stop_count, int extend,\n"
"				     float4 foreground,\n"
"				     device const short4* hb_gpu_atlas)\n"
"{\n"
"  int4 c0_ = int4 (hb_gpu_atlas[grad_base]);\n"
"  int4 c1_ = int4 (hb_gpu_atlas[grad_base + 1]);\n"
"  float2 c0 = float2 (float (c0_.r), float (c0_.g));\n"
"  float r0 = float (c0_.b);\n"
"  float2 c1 = float2 (float (c1_.r), float (c1_.g));\n"
"  float r1 = float (c1_.b);\n"
"\n"
"  float2 cd = c1 - c0;\n"
"  float dr = r1 - r0;\n"
"  float2 p  = renderCoord - c0;\n"
"\n"
"  float A = dot (cd, cd) - dr * dr;\n"
"  float B = -2.0 * (dot (p, cd) + r0 * dr);\n"
"  float C = dot (p, p) - r0 * r0;\n"
"\n"
"  float t;\n"
"  if (abs (A) > 1e-6)\n"
"  {\n"
"    float disc = B * B - 4.0 * A * C;\n"
"    if (disc < 0.0) return float4 (0.0);\n"
"    float sq = sqrt (disc);\n"
"    float t1 = (-B + sq) / (2.0 * A);\n"
"    float t2 = (-B - sq) / (2.0 * A);\n"
"    t = (r0 + t1 * dr >= 0.0) ? t1 : t2;\n"
"  }\n"
"  else\n"
"  {\n"
"    if (abs (B) < 1e-6) return float4 (0.0);\n"
"    t = -C / B;\n"
"  }\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (hb_gpu_atlas, grad_base + 2, stop_count, t, foreground);\n"
"}\n"
"\n"
"static float4 _hb_gpu_sample_sweep (float2 renderCoord, int grad_base,\n"
"				    int stop_count, int extend,\n"
"				    float4 foreground,\n"
"				    device const short4* hb_gpu_atlas)\n"
"{\n"
"  int4 t0 = int4 (hb_gpu_atlas[grad_base]);\n"
"  float2 c = float2 (float (t0.r), float (t0.g));\n"
"  float a0 = float (t0.b) / 16384.0;\n"
"  float a1 = float (t0.a) / 16384.0;\n"
"  float span = a1 - a0;\n"
"  if (abs (span) < 1e-6) return float4 (0.0);\n"
"\n"
"  float2 p = renderCoord - c;\n"
"  float ang = atan2 (p.y, p.x) / 3.14159265358979;\n"
"  if (ang < 0.0) ang += 2.0;\n"
"  float t = (ang - a0) / span;\n"
"  t = _hb_gpu_extend_t (t, extend);\n"
"  return _hb_gpu_eval_stops (hb_gpu_atlas, grad_base + 1, stop_count, t, foreground);\n"
"}\n"
"\n"
"static float4 _hb_gpu_composite (float4 src, float4 dst, int mode)\n"
"{\n"
"  float4 r = src + dst * (1.0 - src.a);  /* SRC_OVER default */\n"
"\n"
"  if      (mode == 0)  r = float4 (0.0);\n"
"  else if (mode == 1)  r = src;\n"
"  else if (mode == 2)  r = dst;\n"
"  else if (mode == 4)  r = dst + src * (1.0 - dst.a);\n"
"  else if (mode == 5)  r = src * dst.a;\n"
"  else if (mode == 6)  r = dst * src.a;\n"
"  else if (mode == 7)  r = src * (1.0 - dst.a);\n"
"  else if (mode == 8)  r = dst * (1.0 - src.a);\n"
"  else if (mode == 9)  r = src * dst.a + dst * (1.0 - src.a);\n"
"  else if (mode == 10) r = dst * src.a + src * (1.0 - dst.a);\n"
"  else if (mode == 11) r = src * (1.0 - dst.a) + dst * (1.0 - src.a);\n"
"  else if (mode == 12) r = min (src + dst, float4 (1.0));\n"
"  else if (mode == 13) {\n"
"    r.rgb = src.rgb + dst.rgb - src.rgb * dst.rgb;\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  else if (mode == 15) {\n"
"    r.rgb = min (src.rgb * dst.a, dst.rgb * src.a)\n"
"          + src.rgb * (1.0 - dst.a) + dst.rgb * (1.0 - src.a);\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  else if (mode == 16) {\n"
"    r.rgb = max (src.rgb * dst.a, dst.rgb * src.a)\n"
"          + src.rgb * (1.0 - dst.a) + dst.rgb * (1.0 - src.a);\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  else if (mode == 23) {\n"
"    r.rgb = src.rgb * (1.0 - dst.a) + dst.rgb * (1.0 - src.a)\n"
"          + src.rgb * dst.rgb;\n"
"    r.a = src.a + dst.a - src.a * dst.a;\n"
"  }\n"
"  return r;\n"
"}\n"
"\n"
"#define HB_GPU_PAINT_GROUP_DEPTH 4\n"
"\n"
"float4 hb_gpu_paint (float2 renderCoord, uint glyphLoc_, float4 foreground,\n"
"		     device const short4* hb_gpu_atlas)\n"
"{\n"
"  /* fwidth once, at uniform control flow. */\n"
"  float2 pixelsPerEm = 1.0 / fwidth (renderCoord);\n"
"\n"
"  int base    = int (glyphLoc_);\n"
"  int4 h0     = int4 (hb_gpu_atlas[base]);       /* (num_ops, _, _, _) */\n"
"  int4 h2     = int4 (hb_gpu_atlas[base + 2]);   /* (ops_offset, _, _, _) */\n"
"  int num_ops = h0.r;\n"
"  int cursor  = base + h2.r;\n"
"\n"
"  float4 acc = float4 (0.0);\n"
"  float4 group_stack[HB_GPU_PAINT_GROUP_DEPTH];\n"
"  int sp = 0;\n"
"\n"
"  for (int i = 0; i < num_ops; i++)\n"
"  {\n"
"    int4 op     = int4 (hb_gpu_atlas[cursor]);\n"
"    int op_type = op.r;\n"
"    int aux     = op.g;\n"
"    int payload = (op.b << 16) | (op.a & 0xffff);\n"
"\n"
"    if (op_type == 0)  /* LAYER_SOLID */\n"
"    {\n"
"      int4 ct = int4 (hb_gpu_atlas[cursor + 1]);\n"
"      float4 col = ((aux & 1) != 0)\n"
"		 ? foreground\n"
"		 : float4 (ct) / 32767.0;\n"
"\n"
"      float cov = _hb_gpu_slug (renderCoord, pixelsPerEm,\n"
"				     uint (base + payload), hb_gpu_atlas);\n"
"      float4 src = float4 (col.rgb * col.a, col.a) * cov;\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor += 2;\n"
"    }\n"
"    else if (op_type == 1)  /* LAYER_GRADIENT */\n"
"    {\n"
"      int4 op2 = int4 (hb_gpu_atlas[cursor + 1]);\n"
"      int grad_payload = (op2.r << 16) | (op2.g & 0xffff);\n"
"      int extend       = op2.b;\n"
"      int stop_count   = op2.a;\n"
"\n"
"      float4 col = float4 (0.0);\n"
"      if (aux == 0)\n"
"        col = _hb_gpu_sample_linear (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground,\n"
"                                     hb_gpu_atlas);\n"
"      else if (aux == 1)\n"
"        col = _hb_gpu_sample_radial (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground,\n"
"                                     hb_gpu_atlas);\n"
"      else if (aux == 2)\n"
"        col = _hb_gpu_sample_sweep  (renderCoord,\n"
"                                     base + grad_payload,\n"
"                                     stop_count, extend, foreground,\n"
"                                     hb_gpu_atlas);\n"
"\n"
"      float cov = _hb_gpu_slug (renderCoord, pixelsPerEm,\n"
"				     uint (base + payload), hb_gpu_atlas);\n"
"      float4 src = float4 (col.rgb * col.a, col.a) * cov;\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor += 2;\n"
"    }\n"
"    else if (op_type == 2)  /* PUSH_GROUP */\n"
"    {\n"
"      if (sp < HB_GPU_PAINT_GROUP_DEPTH) {\n"
"        group_stack[sp] = acc;\n"
"        sp++;\n"
"      }\n"
"      acc = float4 (0.0);\n"
"      cursor += 1;\n"
"    }\n"
"    else if (op_type == 3)  /* POP_GROUP */\n"
"    {\n"
"      if (sp > 0) {\n"
"        sp--;\n"
"        float4 src = acc;\n"
"        float4 dst = group_stack[sp];\n"
"        acc = _hb_gpu_composite (src, dst, aux);\n"
"      }\n"
"      cursor += 1;\n"
"    }\n"
"    else\n"
"    {\n"
"      break;\n"
"    }\n"
"  }\n"
"\n"
"  return acc;\n"
"}\n"
;
