static const char *hb_gpu_paint_fragment_glsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Paint-renderer fragment shader.\n"
" *\n"
" * Assumes the shared fragment helpers (hb-gpu-fragment.glsl) and\n"
" * the draw-renderer fragment helpers (hb-gpu-draw-fragment.glsl)\n"
" * are prepended to this source.  The draw helper provides\n"
" * hb_gpu_draw() which this interpreter calls to compute clip-glyph\n"
" * coverage.\n"
" */\n"
"\n"
"\n"
"#ifndef HB_GPU_PALETTE_SIZE\n"
"#define HB_GPU_PALETTE_SIZE 256\n"
"#endif\n"
"\n"
"uniform vec4 hb_gpu_palette[HB_GPU_PALETTE_SIZE];\n"
"\n"
"\n"
"/* Walks the paint blob's flat op stream and returns a\n"
" * premultiplied RGBA coverage value for the current fragment.\n"
" *\n"
" * glyphLoc: atlas texel offset of the paint-blob header.\n"
" * foreground: caller-supplied foreground color, used when an op\n"
" *             sets the is_foreground flag.\n"
" */\n"
"vec4 hb_gpu_paint (vec2 renderCoord, uint glyphLoc, vec4 foreground)\n"
"{\n"
"  /* fwidth once, at uniform control flow: every per-layer\n"
"   * coverage sample below uses this pre-computed pixelsPerEm via\n"
"   * _hb_gpu_draw_impl. */\n"
"  vec2 pixelsPerEm = 1.0 / fwidth (renderCoord);\n"
"\n"
"  int base    = int (glyphLoc);\n"
"  ivec4 h0    = hb_gpu_fetch (base);      /* (num_ops, _, _, _) */\n"
"  ivec4 h2    = hb_gpu_fetch (base + 2);  /* (ops_offset, _, _, _) */\n"
"  int num_ops = h0.r;\n"
"  int cursor  = base + h2.r;\n"
"\n"
"  vec4 acc = vec4 (0.0);\n"
"\n"
"  for (int i = 0; i < num_ops; i++)\n"
"  {\n"
"    ivec4 op    = hb_gpu_fetch (cursor);\n"
"    int op_type = op.r;\n"
"    int payload = (op.b << 16) | (op.a & 0xffff);\n"
"\n"
"    if (op_type == 0)  /* LAYER_SOLID */\n"
"    {\n"
"      ivec4 ct = hb_gpu_fetch (cursor + 1);\n"
"      int palette_index = ct.r;\n"
"      int flags         = ct.g;\n"
"      float alpha       = float (ct.b) / 32767.0;\n"
"\n"
"      vec4 col = ((flags & 1) != 0)\n"
"	       ? foreground\n"
"	       : hb_gpu_palette[palette_index];\n"
"      col.a *= alpha;\n"
"\n"
"      /* payload is a blob-relative texel offset; sub-blobs live\n"
"       * inside the paint blob at atlas offset `base`. */\n"
"      float cov = _hb_gpu_draw_impl (renderCoord, pixelsPerEm,\n"
"				     uint (base + payload));\n"
"      vec4 src  = col * cov;\n"
"      /* SRC_OVER with premultiplied source. */\n"
"      acc = src + acc * (1.0 - src.a);\n"
"\n"
"      cursor += 2;\n"
"    }\n"
"    else\n"
"    {\n"
"      /* LAYER_GRADIENT, PUSH_GROUP, POP_GROUP not yet handled. */\n"
"      break;\n"
"    }\n"
"  }\n"
"\n"
"  return acc;\n"
"}\n"
;
