static const char *hb_gpu_fragment_glsl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Shared fragment-shader helpers for the hb-gpu renderers.\n"
" *\n"
" * Requires GLSL 3.30 or GLSL ES 3.00.\n"
" *\n"
" * For GLSL ES 3.00 / WebGL2, define HB_GPU_ATLAS_2D before\n"
" * including this source.  The atlas is then a 2D isampler2D\n"
" * texture of known width (set via hb_gpu_atlas_width uniform)\n"
" * instead of an isamplerBuffer.\n"
" */\n"
"\n"
"\n"
"#ifndef HB_GPU_UNITS_PER_EM\n"
"#define HB_GPU_UNITS_PER_EM 4\n"
"#endif\n"
"\n"
"#define HB_GPU_INV_UNITS float(1.0 / float(HB_GPU_UNITS_PER_EM))\n"
"\n"
"\n"
"#ifdef HB_GPU_ATLAS_2D\n"
"uniform highp isampler2D hb_gpu_atlas;\n"
"uniform int hb_gpu_atlas_width;\n"
"ivec4 hb_gpu_fetch (int offset)\n"
"{\n"
"  return texelFetch (hb_gpu_atlas,\n"
"		     ivec2 (offset % hb_gpu_atlas_width,\n"
"			    offset / hb_gpu_atlas_width), 0);\n"
"}\n"
"#else\n"
"uniform isamplerBuffer hb_gpu_atlas;\n"
"ivec4 hb_gpu_fetch (int offset)\n"
"{\n"
"  return texelFetch (hb_gpu_atlas, offset);\n"
"}\n"
"#endif\n"
;
