static const char *hb_gpu_fragment_msl =
"/*\n"
" * Copyright (C) 2026  Behdad Esfahbod\n"
" * Copyright (C) 2017  Eric Lengyel\n"
" *\n"
" * Based on the Slug algorithm by Eric Lengyel:\n"
" * https://github.com/EricLengyel/Slug\n"
" *\n"
" *  This is part of HarfBuzz, a text shaping library.\n"
" *\n"
" * Permission is hereby granted, without written agreement and without\n"
" * license or royalty fees, to use, copy, modify, and distribute this\n"
" * software and its documentation for any purpose, provided that the\n"
" * above copyright notice and the following two paragraphs appear in\n"
" * all copies of this software.\n"
" *\n"
" * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR\n"
" * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES\n"
" * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN\n"
" * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" *\n"
" * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\n"
" * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS\n"
" * ON AN \"AS IS\" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO\n"
" * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n"
" */\n"
"\n"
"\n"
"/* Requires Metal Shading Language 2.0. */\n"
"\n"
"\n"
"#ifndef HB_GPU_UNITS_PER_EM\n"
"#define HB_GPU_UNITS_PER_EM 4\n"
"#endif\n"
"\n"
"#define HB_GPU_INV_UNITS float(1.0 / float(HB_GPU_UNITS_PER_EM))\n"
"\n"
"\n"
"int4 _hb_gpu_fetch (device const short4* hb_gpu_atlas, int offset)\n"
"{\n"
"  return int4 (hb_gpu_atlas[offset]);\n"
"}\n"
"\n"
"\n"
"uint _hb_gpu_calc_root_code (float y1, float y2, float y3)\n"
"{\n"
"  uint i1 = as_type<uint> (y1) >> 31U;\n"
"  uint i2 = as_type<uint> (y2) >> 30U;\n"
"  uint i3 = as_type<uint> (y3) >> 29U;\n"
"\n"
"  uint shift = (i2 & 2U) | (i1 & ~2U);\n"
"  shift = (i3 & 4U) | (shift & ~4U);\n"
"\n"
"  return (0x2E74U >> shift) & 0x0101U;\n"
"}\n"
"\n"
"float2 _hb_gpu_solve_horiz_poly (float2 a, float2 b, float2 p1)\n"
"{\n"
"  float ra = 1.0 / a.y;\n"
"  float rb = 0.5 / b.y;\n"
"\n"
"  float d = sqrt (max (b.y * b.y - a.y * p1.y, 0.0));\n"
"  float t1 = (b.y - d) * ra;\n"
"  float t2 = (b.y + d) * ra;\n"
"\n"
"  if (a.y == 0.0)\n"
"    t1 = t2 = p1.y * rb;\n"
"\n"
"  return float2 ((a.x * t1 - b.x * 2.0) * t1 + p1.x,\n"
"		 (a.x * t2 - b.x * 2.0) * t2 + p1.x);\n"
"}\n"
"\n"
"float2 _hb_gpu_solve_vert_poly (float2 a, float2 b, float2 p1)\n"
"{\n"
"  float ra = 1.0 / a.x;\n"
"  float rb = 0.5 / b.x;\n"
"\n"
"  float d = sqrt (max (b.x * b.x - a.x * p1.x, 0.0));\n"
"  float t1 = (b.x - d) * ra;\n"
"  float t2 = (b.x + d) * ra;\n"
"\n"
"  if (a.x == 0.0)\n"
"    t1 = t2 = p1.x * rb;\n"
"\n"
"  return float2 ((a.y * t1 - b.y * 2.0) * t1 + p1.y,\n"
"		 (a.y * t2 - b.y * 2.0) * t2 + p1.y);\n"
"}\n"
"\n"
"float _hb_gpu_calc_coverage (float xcov, float ycov, float xwgt, float ywgt)\n"
"{\n"
"  float coverage = max (abs (xcov * xwgt + ycov * ywgt) /\n"
"			max (xwgt + ywgt, 1.0 / 65536.0),\n"
"			min (abs (xcov), abs (ycov)));\n"
"\n"
"  return clamp (coverage, 0.0, 1.0);\n"
"}\n"
"\n"
"/* Render a glyph and return its coverage in [0, 1].\n"
" *\n"
" * Requires hb_gpu_atlas to point to the glyph atlas buffer.\n"
" *\n"
" * renderCoord:  em-space sample position (interpolated from vertex shader)\n"
" * glyphLoc:     offset into hb_gpu_atlas for this glyph's encoded blob\n"
" * hb_gpu_atlas: device pointer to the glyph atlas buffer\n"
" */\n"
"float hb_gpu_render (float2 renderCoord, uint glyphLoc_,\n"
"		     device const short4* hb_gpu_atlas)\n"
"{\n"
"  float2 emsPerPixel = fwidth (renderCoord);\n"
"  float2 pixelsPerEm = 1.0 / emsPerPixel;\n"
"\n"
"  int glyphLoc = int (glyphLoc_);\n"
"\n"
"  /* Read blob header */\n"
"  int4 header0 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc);\n"
"  int4 header1 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + 1);\n"
"  float4 ext = float4 (header0) * HB_GPU_INV_UNITS; /* min_x, min_y, max_x, max_y */\n"
"  int numHBands = header1.r;\n"
"  int numVBands = header1.g;\n"
"\n"
"  /* Compute band transform from extents */\n"
"  float2 extSize = ext.zw - ext.xy; /* (width, height) */\n"
"  float2 bandScale = float2 (float (numVBands), float (numHBands)) / max (extSize, float2 (1.0 / 65536.0));\n"
"  float2 bandOffset = -ext.xy * bandScale;\n"
"\n"
"  int2 bandIndex = clamp (int2 (renderCoord * bandScale + bandOffset),\n"
"			  int2 (0, 0),\n"
"			  int2 (numVBands - 1, numHBands - 1));\n"
"\n"
"  /* Skip past header (2 texels) */\n"
"  int bandBase = glyphLoc + 2;\n"
"\n"
"  float xcov = 0.0;\n"
"  float xwgt = 0.0;\n"
"\n"
"  int4 hbandData = _hb_gpu_fetch (hb_gpu_atlas, bandBase + bandIndex.y);\n"
"  int hCurveCount = hbandData.r;\n"
"  /* Symmetric: choose rightward (desc) or leftward (asc) sort */\n"
"  float hSplit = float (hbandData.a) * HB_GPU_INV_UNITS;\n"
"  bool hLeftRay = (renderCoord.x < hSplit);\n"
"  int hDataOffset = (hLeftRay ? hbandData.b : hbandData.g) + 32768;\n"
"\n"
"  for (int ci = 0; ci < hCurveCount; ci++)\n"
"  {\n"
"    int curveOffset = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + hDataOffset + ci).r + 32768;\n"
"\n"
"    int4 raw12 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset);\n"
"    int4 raw3 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset + 1);\n"
"\n"
"    float4 q12 = float4 (raw12) * HB_GPU_INV_UNITS;\n"
"    float2 q3 = float2 (raw3.rg) * HB_GPU_INV_UNITS;\n"
"\n"
"    float4 p12 = q12 - float4 (renderCoord, renderCoord);\n"
"    float2 p3 = q3 - renderCoord;\n"
"\n"
"    if (hLeftRay) {\n"
"      if (min (min (p12.x, p12.z), p3.x) * pixelsPerEm.x > 0.5) break;\n"
"    } else {\n"
"      if (max (max (p12.x, p12.z), p3.x) * pixelsPerEm.x < -0.5) break;\n"
"    }\n"
"\n"
"    uint code = _hb_gpu_calc_root_code (p12.y, p12.w, p3.y);\n"
"    if (code != 0U)\n"
"    {\n"
"      float2 a = q12.xy - q12.zw * 2.0 + q3;\n"
"      float2 b = q12.xy - q12.zw;\n"
"      float2 r = _hb_gpu_solve_horiz_poly (a, b, p12.xy) * pixelsPerEm.x;\n"
"      /* For leftward ray: saturate(0.5 - r) counts coverage from the left */\n"
"      float2 cov = hLeftRay ? clamp (float2 (0.5) - r, 0.0, 1.0)\n"
"			    : clamp (r + float2 (0.5), 0.0, 1.0);\n"
"\n"
"      if ((code & 1U) != 0U)\n"
"      {\n"
"	xcov += cov.x;\n"
"	xwgt = max (xwgt, clamp (1.0 - abs (r.x) * 2.0, 0.0, 1.0));\n"
"      }\n"
"\n"
"      if (code > 1U)\n"
"      {\n"
"	xcov -= cov.y;\n"
"	xwgt = max (xwgt, clamp (1.0 - abs (r.y) * 2.0, 0.0, 1.0));\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  float ycov = 0.0;\n"
"  float ywgt = 0.0;\n"
"\n"
"  int4 vbandData = _hb_gpu_fetch (hb_gpu_atlas, bandBase + numHBands + bandIndex.x);\n"
"  int vCurveCount = vbandData.r;\n"
"  float vSplit = float (vbandData.a) * HB_GPU_INV_UNITS;\n"
"  bool vLeftRay = (renderCoord.y < vSplit);\n"
"  int vDataOffset = (vLeftRay ? vbandData.b : vbandData.g) + 32768;\n"
"\n"
"  for (int ci = 0; ci < vCurveCount; ci++)\n"
"  {\n"
"    int curveOffset = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + vDataOffset + ci).r + 32768;\n"
"\n"
"    int4 raw12 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset);\n"
"    int4 raw3 = _hb_gpu_fetch (hb_gpu_atlas, glyphLoc + curveOffset + 1);\n"
"\n"
"    float4 q12 = float4 (raw12) * HB_GPU_INV_UNITS;\n"
"    float2 q3 = float2 (raw3.rg) * HB_GPU_INV_UNITS;\n"
"\n"
"    float4 p12 = q12 - float4 (renderCoord, renderCoord);\n"
"    float2 p3 = q3 - renderCoord;\n"
"\n"
"    if (vLeftRay) {\n"
"      if (min (min (p12.y, p12.w), p3.y) * pixelsPerEm.y > 0.5) break;\n"
"    } else {\n"
"      if (max (max (p12.y, p12.w), p3.y) * pixelsPerEm.y < -0.5) break;\n"
"    }\n"
"\n"
"    uint code = _hb_gpu_calc_root_code (p12.x, p12.z, p3.x);\n"
"    if (code != 0U)\n"
"    {\n"
"      float2 a = q12.xy - q12.zw * 2.0 + q3;\n"
"      float2 b = q12.xy - q12.zw;\n"
"      float2 r = _hb_gpu_solve_vert_poly (a, b, p12.xy) * pixelsPerEm.y;\n"
"      float2 cov = vLeftRay ? clamp (float2 (0.5) - r, 0.0, 1.0)\n"
"			    : clamp (r + float2 (0.5), 0.0, 1.0);\n"
"\n"
"      if ((code & 1U) != 0U)\n"
"      {\n"
"	ycov -= cov.x;\n"
"	ywgt = max (ywgt, clamp (1.0 - abs (r.x) * 2.0, 0.0, 1.0));\n"
"      }\n"
"\n"
"      if (code > 1U)\n"
"      {\n"
"	ycov += cov.y;\n"
"	ywgt = max (ywgt, clamp (1.0 - abs (r.y) * 2.0, 0.0, 1.0));\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  return _hb_gpu_calc_coverage (xcov, ycov, xwgt, ywgt);\n"
"}\n"
;
