/* == Start of generated table == */
/*
 * The following table is generated by running:
 *
 *   ./gen-arabic-table.py ArabicShaping.txt UnicodeData.txt Blocks.txt
 *
 * on files with these headers:
 *
 * # ArabicShaping-6.2.0.txt
 * # Date: 2012-05-15, 21:05:00 GMT [KW]
 * # Blocks-6.2.0.txt
 * # Date: 2012-05-14, 22:42:00 GMT [KW, LI]
 * UnicodeData.txt does not have a header.
 */

#ifndef HB_OT_SHAPE_COMPLEX_ARABIC_TABLE_HH
#define HB_OT_SHAPE_COMPLEX_ARABIC_TABLE_HH


#define X	JOINING_TYPE_X
#define R	JOINING_TYPE_R
#define U	JOINING_TYPE_U
#define A	JOINING_GROUP_ALAPH
#define DR	JOINING_GROUP_DALATH_RISH
#define C	JOINING_TYPE_C
#define D	JOINING_TYPE_D

static const uint8_t joining_table[] =
{

  /* Arabic */

  U, /* 0600; ARABIC NUMBER SIGN; U; No_Joining_Group */
  U, /* 0601; ARABIC SIGN SANAH; U; No_Joining_Group */
  U, /* 0602; ARABIC FOOTNOTE MARKER; U; No_Joining_Group */
  U, /* 0603; ARABIC SIGN SAFHA; U; No_Joining_Group */
  U, /* 0604; ARABIC SIGN SAMVAT; U; No_Joining_Group */
  X, /* 0605 */
  X, /* 0606 */
  X, /* 0607 */
  U, /* 0608; ARABIC RAY; U; No_Joining_Group */
  X, /* 0609 */
  X, /* 060A */
  U, /* 060B; AFGHANI SIGN; U; No_Joining_Group */
  X, /* 060C */
  X, /* 060D */
  X, /* 060E */
  X, /* 060F */
  X, /* 0610 */
  X, /* 0611 */
  X, /* 0612 */
  X, /* 0613 */
  X, /* 0614 */
  X, /* 0615 */
  X, /* 0616 */
  X, /* 0617 */
  X, /* 0618 */
  X, /* 0619 */
  X, /* 061A */
  X, /* 061B */
  X, /* 061C */
  X, /* 061D */
  X, /* 061E */
  X, /* 061F */
  D, /* 0620; DOTLESS YEH WITH SEPARATE RING BELOW; D; YEH */
  U, /* 0621; HAMZA; U; No_Joining_Group */
  R, /* 0622; ALEF WITH MADDA ABOVE; R; ALEF */
  R, /* 0623; ALEF WITH HAMZA ABOVE; R; ALEF */
  R, /* 0624; WAW WITH HAMZA ABOVE; R; WAW */
  R, /* 0625; ALEF WITH HAMZA BELOW; R; ALEF */
  D, /* 0626; DOTLESS YEH WITH HAMZA ABOVE; D; YEH */
  R, /* 0627; ALEF; R; ALEF */
  D, /* 0628; BEH; D; BEH */
  R, /* 0629; TEH MARBUTA; R; TEH MARBUTA */
  D, /* 062A; DOTLESS BEH WITH 2 DOTS ABOVE; D; BEH */
  D, /* 062B; DOTLESS BEH WITH 3 DOTS ABOVE; D; BEH */
  D, /* 062C; HAH WITH DOT BELOW; D; HAH */
  D, /* 062D; HAH; D; HAH */
  D, /* 062E; HAH WITH DOT ABOVE; D; HAH */
  R, /* 062F; DAL; R; DAL */
  R, /* 0630; DAL WITH DOT ABOVE; R; DAL */
  R, /* 0631; REH; R; REH */
  R, /* 0632; REH WITH DOT ABOVE; R; REH */
  D, /* 0633; SEEN; D; SEEN */
  D, /* 0634; SEEN WITH 3 DOTS ABOVE; D; SEEN */
  D, /* 0635; SAD; D; SAD */
  D, /* 0636; SAD WITH DOT ABOVE; D; SAD */
  D, /* 0637; TAH; D; TAH */
  D, /* 0638; TAH WITH DOT ABOVE; D; TAH */
  D, /* 0639; AIN; D; AIN */
  D, /* 063A; AIN WITH DOT ABOVE; D; AIN */
  D, /* 063B; KEHEH WITH 2 DOTS ABOVE; D; GAF */
  D, /* 063C; KEHEH WITH 3 DOTS BELOW; D; GAF */
  D, /* 063D; FARSI YEH WITH INVERTED V ABOVE; D; FARSI YEH */
  D, /* 063E; FARSI YEH WITH 2 DOTS ABOVE; D; FARSI YEH */
  D, /* 063F; FARSI YEH WITH 3 DOTS ABOVE; D; FARSI YEH */
  C, /* 0640; TATWEEL; C; No_Joining_Group */
  D, /* 0641; FEH; D; FEH */
  D, /* 0642; QAF; D; QAF */
  D, /* 0643; KAF; D; KAF */
  D, /* 0644; LAM; D; LAM */
  D, /* 0645; MEEM; D; MEEM */
  D, /* 0646; NOON; D; NOON */
  D, /* 0647; HEH; D; HEH */
  R, /* 0648; WAW; R; WAW */
  D, /* 0649; DOTLESS YEH; D; YEH */
  D, /* 064A; YEH; D; YEH */
  X, /* 064B */
  X, /* 064C */
  X, /* 064D */
  X, /* 064E */
  X, /* 064F */
  X, /* 0650 */
  X, /* 0651 */
  X, /* 0652 */
  X, /* 0653 */
  X, /* 0654 */
  X, /* 0655 */
  X, /* 0656 */
  X, /* 0657 */
  X, /* 0658 */
  X, /* 0659 */
  X, /* 065A */
  X, /* 065B */
  X, /* 065C */
  X, /* 065D */
  X, /* 065E */
  X, /* 065F */
  X, /* 0660 */
  X, /* 0661 */
  X, /* 0662 */
  X, /* 0663 */
  X, /* 0664 */
  X, /* 0665 */
  X, /* 0666 */
  X, /* 0667 */
  X, /* 0668 */
  X, /* 0669 */
  X, /* 066A */
  X, /* 066B */
  X, /* 066C */
  X, /* 066D */
  D, /* 066E; DOTLESS BEH; D; BEH */
  D, /* 066F; DOTLESS QAF; D; QAF */
  X, /* 0670 */
  R, /* 0671; ALEF WITH WASLA ABOVE; R; ALEF */
  R, /* 0672; ALEF WITH WAVY HAMZA ABOVE; R; ALEF */
  R, /* 0673; ALEF WITH WAVY HAMZA BELOW; R; ALEF */
  U, /* 0674; HIGH HAMZA; U; No_Joining_Group */
  R, /* 0675; HIGH HAMZA ALEF; R; ALEF */
  R, /* 0676; HIGH HAMZA WAW; R; WAW */
  R, /* 0677; HIGH HAMZA WAW WITH DAMMA ABOVE; R; WAW */
  D, /* 0678; HIGH HAMZA DOTLESS YEH; D; YEH */
  D, /* 0679; DOTLESS BEH WITH TAH ABOVE; D; BEH */
  D, /* 067A; DOTLESS BEH WITH VERTICAL 2 DOTS ABOVE; D; BEH */
  D, /* 067B; DOTLESS BEH WITH VERTICAL 2 DOTS BELOW; D; BEH */
  D, /* 067C; DOTLESS BEH WITH ATTACHED RING BELOW AND 2 DOTS ABOVE; D; BEH */
  D, /* 067D; DOTLESS BEH WITH INVERTED 3 DOTS ABOVE; D; BEH */
  D, /* 067E; DOTLESS BEH WITH 3 DOTS BELOW; D; BEH */
  D, /* 067F; DOTLESS BEH WITH 4 DOTS ABOVE; D; BEH */
  D, /* 0680; DOTLESS BEH WITH 4 DOTS BELOW; D; BEH */
  D, /* 0681; HAH WITH HAMZA ABOVE; D; HAH */
  D, /* 0682; HAH WITH VERTICAL 2 DOTS ABOVE; D; HAH */
  D, /* 0683; HAH WITH 2 DOTS BELOW; D; HAH */
  D, /* 0684; HAH WITH VERTICAL 2 DOTS BELOW; D; HAH */
  D, /* 0685; HAH WITH 3 DOTS ABOVE; D; HAH */
  D, /* 0686; HAH WITH 3 DOTS BELOW; D; HAH */
  D, /* 0687; HAH WITH 4 DOTS BELOW; D; HAH */
  R, /* 0688; DAL WITH TAH ABOVE; R; DAL */
  R, /* 0689; DAL WITH ATTACHED RING BELOW; R; DAL */
  R, /* 068A; DAL WITH DOT BELOW; R; DAL */
  R, /* 068B; DAL WITH DOT BELOW AND TAH ABOVE; R; DAL */
  R, /* 068C; DAL WITH 2 DOTS ABOVE; R; DAL */
  R, /* 068D; DAL WITH 2 DOTS BELOW; R; DAL */
  R, /* 068E; DAL WITH 3 DOTS ABOVE; R; DAL */
  R, /* 068F; DAL WITH INVERTED 3 DOTS ABOVE; R; DAL */
  R, /* 0690; DAL WITH 4 DOTS ABOVE; R; DAL */
  R, /* 0691; REH WITH TAH ABOVE; R; REH */
  R, /* 0692; REH WITH V ABOVE; R; REH */
  R, /* 0693; REH WITH ATTACHED RING BELOW; R; REH */
  R, /* 0694; REH WITH DOT BELOW; R; REH */
  R, /* 0695; REH WITH V BELOW; R; REH */
  R, /* 0696; REH WITH DOT BELOW AND DOT WITHIN; R; REH */
  R, /* 0697; REH WITH 2 DOTS ABOVE; R; REH */
  R, /* 0698; REH WITH 3 DOTS ABOVE; R; REH */
  R, /* 0699; REH WITH 4 DOTS ABOVE; R; REH */
  D, /* 069A; SEEN WITH DOT BELOW AND DOT ABOVE; D; SEEN */
  D, /* 069B; SEEN WITH 3 DOTS BELOW; D; SEEN */
  D, /* 069C; SEEN WITH 3 DOTS BELOW AND 3 DOTS ABOVE; D; SEEN */
  D, /* 069D; SAD WITH 2 DOTS BELOW; D; SAD */
  D, /* 069E; SAD WITH 3 DOTS ABOVE; D; SAD */
  D, /* 069F; TAH WITH 3 DOTS ABOVE; D; TAH */
  D, /* 06A0; AIN WITH 3 DOTS ABOVE; D; AIN */
  D, /* 06A1; DOTLESS FEH; D; FEH */
  D, /* 06A2; DOTLESS FEH WITH DOT BELOW; D; FEH */
  D, /* 06A3; FEH WITH DOT BELOW; D; FEH */
  D, /* 06A4; DOTLESS FEH WITH 3 DOTS ABOVE; D; FEH */
  D, /* 06A5; DOTLESS FEH WITH 3 DOTS BELOW; D; FEH */
  D, /* 06A6; DOTLESS FEH WITH 4 DOTS ABOVE; D; FEH */
  D, /* 06A7; DOTLESS QAF WITH DOT ABOVE; D; QAF */
  D, /* 06A8; DOTLESS QAF WITH 3 DOTS ABOVE; D; QAF */
  D, /* 06A9; KEHEH; D; GAF */
  D, /* 06AA; SWASH KAF; D; SWASH KAF */
  D, /* 06AB; KEHEH WITH ATTACHED RING BELOW; D; GAF */
  D, /* 06AC; KAF WITH DOT ABOVE; D; KAF */
  D, /* 06AD; KAF WITH 3 DOTS ABOVE; D; KAF */
  D, /* 06AE; KAF WITH 3 DOTS BELOW; D; KAF */
  D, /* 06AF; GAF; D; GAF */
  D, /* 06B0; GAF WITH ATTACHED RING BELOW; D; GAF */
  D, /* 06B1; GAF WITH 2 DOTS ABOVE; D; GAF */
  D, /* 06B2; GAF WITH 2 DOTS BELOW; D; GAF */
  D, /* 06B3; GAF WITH VERTICAL 2 DOTS BELOW; D; GAF */
  D, /* 06B4; GAF WITH 3 DOTS ABOVE; D; GAF */
  D, /* 06B5; LAM WITH V ABOVE; D; LAM */
  D, /* 06B6; LAM WITH DOT ABOVE; D; LAM */
  D, /* 06B7; LAM WITH 3 DOTS ABOVE; D; LAM */
  D, /* 06B8; LAM WITH 3 DOTS BELOW; D; LAM */
  D, /* 06B9; NOON WITH DOT BELOW; D; NOON */
  D, /* 06BA; DOTLESS NOON; D; NOON */
  D, /* 06BB; DOTLESS NOON WITH TAH ABOVE; D; NOON */
  D, /* 06BC; NOON WITH ATTACHED RING BELOW; D; NOON */
  D, /* 06BD; NYA; D; NYA */
  D, /* 06BE; KNOTTED HEH; D; KNOTTED HEH */
  D, /* 06BF; HAH WITH 3 DOTS BELOW AND DOT ABOVE; D; HAH */
  R, /* 06C0; DOTLESS TEH MARBUTA WITH HAMZA ABOVE; R; TEH MARBUTA */
  D, /* 06C1; HEH GOAL; D; HEH GOAL */
  D, /* 06C2; HEH GOAL WITH HAMZA ABOVE; D; HEH GOAL */
  R, /* 06C3; TEH MARBUTA GOAL; R; TEH MARBUTA GOAL */
  R, /* 06C4; WAW WITH ATTACHED RING WITHIN; R; WAW */
  R, /* 06C5; WAW WITH BAR; R; WAW */
  R, /* 06C6; WAW WITH V ABOVE; R; WAW */
  R, /* 06C7; WAW WITH DAMMA ABOVE; R; WAW */
  R, /* 06C8; WAW WITH ALEF ABOVE; R; WAW */
  R, /* 06C9; WAW WITH INVERTED V ABOVE; R; WAW */
  R, /* 06CA; WAW WITH 2 DOTS ABOVE; R; WAW */
  R, /* 06CB; WAW WITH 3 DOTS ABOVE; R; WAW */
  D, /* 06CC; FARSI YEH; D; FARSI YEH */
  R, /* 06CD; YEH WITH TAIL; R; YEH WITH TAIL */
  D, /* 06CE; FARSI YEH WITH V ABOVE; D; FARSI YEH */
  R, /* 06CF; WAW WITH DOT ABOVE; R; WAW */
  D, /* 06D0; DOTLESS YEH WITH VERTICAL 2 DOTS BELOW; D; YEH */
  D, /* 06D1; DOTLESS YEH WITH 3 DOTS BELOW; D; YEH */
  R, /* 06D2; YEH BARREE; R; YEH BARREE */
  R, /* 06D3; YEH BARREE WITH HAMZA ABOVE; R; YEH BARREE */
  X, /* 06D4 */
  R, /* 06D5; DOTLESS TEH MARBUTA; R; TEH MARBUTA */
  X, /* 06D6 */
  X, /* 06D7 */
  X, /* 06D8 */
  X, /* 06D9 */
  X, /* 06DA */
  X, /* 06DB */
  X, /* 06DC */
  U, /* 06DD; ARABIC END OF AYAH; U; No_Joining_Group */
  X, /* 06DE */
  X, /* 06DF */
  X, /* 06E0 */
  X, /* 06E1 */
  X, /* 06E2 */
  X, /* 06E3 */
  X, /* 06E4 */
  X, /* 06E5 */
  X, /* 06E6 */
  X, /* 06E7 */
  X, /* 06E8 */
  X, /* 06E9 */
  X, /* 06EA */
  X, /* 06EB */
  X, /* 06EC */
  X, /* 06ED */
  R, /* 06EE; DAL WITH INVERTED V ABOVE; R; DAL */
  R, /* 06EF; REH WITH INVERTED V ABOVE; R; REH */
  X, /* 06F0 */
  X, /* 06F1 */
  X, /* 06F2 */
  X, /* 06F3 */
  X, /* 06F4 */
  X, /* 06F5 */
  X, /* 06F6 */
  X, /* 06F7 */
  X, /* 06F8 */
  X, /* 06F9 */
  D, /* 06FA; SEEN WITH DOT BELOW AND 3 DOTS ABOVE; D; SEEN */
  D, /* 06FB; SAD WITH DOT BELOW AND DOT ABOVE; D; SAD */
  D, /* 06FC; AIN WITH DOT BELOW AND DOT ABOVE; D; AIN */
  X, /* 06FD */
  X, /* 06FE */
  D, /* 06FF; KNOTTED HEH WITH INVERTED V ABOVE; D; KNOTTED HEH */

  /* Syriac */

  X, /* 0700 */
  X, /* 0701 */
  X, /* 0702 */
  X, /* 0703 */
  X, /* 0704 */
  X, /* 0705 */
  X, /* 0706 */
  X, /* 0707 */
  X, /* 0708 */
  X, /* 0709 */
  X, /* 070A */
  X, /* 070B */
  X, /* 070C */
  X, /* 070D */
  X, /* 070E */
  X, /* 070F */
  A, /* 0710; ALAPH; R; ALAPH */
  X, /* 0711 */
  D, /* 0712; BETH; D; BETH */
  D, /* 0713; GAMAL; D; GAMAL */
  D, /* 0714; GAMAL GARSHUNI; D; GAMAL */
  DR, /* 0715; DALATH; R; DALATH RISH */
  DR, /* 0716; DOTLESS DALATH RISH; R; DALATH RISH */
  R, /* 0717; HE; R; HE */
  R, /* 0718; WAW; R; SYRIAC WAW */
  R, /* 0719; ZAIN; R; ZAIN */
  D, /* 071A; HETH; D; HETH */
  D, /* 071B; TETH; D; TETH */
  D, /* 071C; TETH GARSHUNI; D; TETH */
  D, /* 071D; YUDH; D; YUDH */
  R, /* 071E; YUDH HE; R; YUDH HE */
  D, /* 071F; KAPH; D; KAPH */
  D, /* 0720; LAMADH; D; LAMADH */
  D, /* 0721; MIM; D; MIM */
  D, /* 0722; NUN; D; NUN */
  D, /* 0723; SEMKATH; D; SEMKATH */
  D, /* 0724; FINAL SEMKATH; D; FINAL SEMKATH */
  D, /* 0725; E; D; E */
  D, /* 0726; PE; D; PE */
  D, /* 0727; REVERSED PE; D; REVERSED PE */
  R, /* 0728; SADHE; R; SADHE */
  D, /* 0729; QAPH; D; QAPH */
  DR, /* 072A; RISH; R; DALATH RISH */
  D, /* 072B; SHIN; D; SHIN */
  R, /* 072C; TAW; R; TAW */
  D, /* 072D; PERSIAN BHETH; D; BETH */
  D, /* 072E; PERSIAN GHAMAL; D; GAMAL */
  DR, /* 072F; PERSIAN DHALATH; R; DALATH RISH */
  X, /* 0730 */
  X, /* 0731 */
  X, /* 0732 */
  X, /* 0733 */
  X, /* 0734 */
  X, /* 0735 */
  X, /* 0736 */
  X, /* 0737 */
  X, /* 0738 */
  X, /* 0739 */
  X, /* 073A */
  X, /* 073B */
  X, /* 073C */
  X, /* 073D */
  X, /* 073E */
  X, /* 073F */
  X, /* 0740 */
  X, /* 0741 */
  X, /* 0742 */
  X, /* 0743 */
  X, /* 0744 */
  X, /* 0745 */
  X, /* 0746 */
  X, /* 0747 */
  X, /* 0748 */
  X, /* 0749 */
  X, /* 074A */
  X, /* 074B */
  X, /* 074C */
  R, /* 074D; SOGDIAN ZHAIN; R; ZHAIN */
  D, /* 074E; SOGDIAN KHAPH; D; KHAPH */
  D, /* 074F; SOGDIAN FE; D; FE */

  /* Arabic Supplement */

  D, /* 0750; DOTLESS BEH WITH HORIZONTAL 3 DOTS BELOW; D; BEH */
  D, /* 0751; BEH WITH 3 DOTS ABOVE; D; BEH */
  D, /* 0752; DOTLESS BEH WITH INVERTED 3 DOTS BELOW; D; BEH */
  D, /* 0753; DOTLESS BEH WITH INVERTED 3 DOTS BELOW AND 2 DOTS ABOVE; D; BEH */
  D, /* 0754; DOTLESS BEH WITH 2 DOTS BELOW AND DOT ABOVE; D; BEH */
  D, /* 0755; DOTLESS BEH WITH INVERTED V BELOW; D; BEH */
  D, /* 0756; DOTLESS BEH WITH V ABOVE; D; BEH */
  D, /* 0757; HAH WITH 2 DOTS ABOVE; D; HAH */
  D, /* 0758; HAH WITH INVERTED 3 DOTS BELOW; D; HAH */
  R, /* 0759; DAL WITH VERTICAL 2 DOTS BELOW AND TAH ABOVE; R; DAL */
  R, /* 075A; DAL WITH INVERTED V BELOW; R; DAL */
  R, /* 075B; REH WITH BAR; R; REH */
  D, /* 075C; SEEN WITH 4 DOTS ABOVE; D; SEEN */
  D, /* 075D; AIN WITH 2 DOTS ABOVE; D; AIN */
  D, /* 075E; AIN WITH INVERTED 3 DOTS ABOVE; D; AIN */
  D, /* 075F; AIN WITH VERTICAL 2 DOTS ABOVE; D; AIN */
  D, /* 0760; DOTLESS FEH WITH 2 DOTS BELOW; D; FEH */
  D, /* 0761; DOTLESS FEH WITH INVERTED 3 DOTS BELOW; D; FEH */
  D, /* 0762; KEHEH WITH DOT ABOVE; D; GAF */
  D, /* 0763; KEHEH WITH 3 DOTS ABOVE; D; GAF */
  D, /* 0764; KEHEH WITH INVERTED 3 DOTS BELOW; D; GAF */
  D, /* 0765; MEEM WITH DOT ABOVE; D; MEEM */
  D, /* 0766; MEEM WITH DOT BELOW; D; MEEM */
  D, /* 0767; NOON WITH 2 DOTS BELOW; D; NOON */
  D, /* 0768; NOON WITH TAH ABOVE; D; NOON */
  D, /* 0769; NOON WITH V ABOVE; D; NOON */
  D, /* 076A; LAM WITH BAR; D; LAM */
  R, /* 076B; REH WITH VERTICAL 2 DOTS ABOVE; R; REH */
  R, /* 076C; REH WITH HAMZA ABOVE; R; REH */
  D, /* 076D; SEEN WITH VERTICAL 2 DOTS ABOVE; D; SEEN */
  D, /* 076E; HAH WITH TAH BELOW; D; HAH */
  D, /* 076F; HAH WITH TAH AND 2 DOTS BELOW; D; HAH */
  D, /* 0770; SEEN WITH 2 DOTS AND TAH ABOVE; D; SEEN */
  R, /* 0771; REH WITH 2 DOTS AND TAH ABOVE; R; REH */
  D, /* 0772; HAH WITH TAH ABOVE; D; HAH */
  R, /* 0773; ALEF WITH DIGIT TWO ABOVE; R; ALEF */
  R, /* 0774; ALEF WITH DIGIT THREE ABOVE; R; ALEF */
  D, /* 0775; FARSI YEH WITH DIGIT TWO ABOVE; D; FARSI YEH */
  D, /* 0776; FARSI YEH WITH DIGIT THREE ABOVE; D; FARSI YEH */
  D, /* 0777; DOTLESS YEH WITH DIGIT FOUR BELOW; D; YEH */
  R, /* 0778; WAW WITH DIGIT TWO ABOVE; R; WAW */
  R, /* 0779; WAW WITH DIGIT THREE ABOVE; R; WAW */
  D, /* 077A; BURUSHASKI YEH BARREE WITH DIGIT TWO ABOVE; D; BURUSHASKI YEH BARREE */
  D, /* 077B; BURUSHASKI YEH BARREE WITH DIGIT THREE ABOVE; D; BURUSHASKI YEH BARREE */
  D, /* 077C; HAH WITH DIGIT FOUR BELOW; D; HAH */
  D, /* 077D; SEEN WITH DIGIT FOUR ABOVE; D; SEEN */
  D, /* 077E; SEEN WITH INVERTED V ABOVE; D; SEEN */
  D, /* 077F; KAF WITH 2 DOTS ABOVE; D; KAF */

  /* Thaana */

  X, /* 0780 */
  X, /* 0781 */
  X, /* 0782 */
  X, /* 0783 */
  X, /* 0784 */
  X, /* 0785 */
  X, /* 0786 */
  X, /* 0787 */
  X, /* 0788 */
  X, /* 0789 */
  X, /* 078A */
  X, /* 078B */
  X, /* 078C */
  X, /* 078D */
  X, /* 078E */
  X, /* 078F */
  X, /* 0790 */
  X, /* 0791 */
  X, /* 0792 */
  X, /* 0793 */
  X, /* 0794 */
  X, /* 0795 */
  X, /* 0796 */
  X, /* 0797 */
  X, /* 0798 */
  X, /* 0799 */
  X, /* 079A */
  X, /* 079B */
  X, /* 079C */
  X, /* 079D */
  X, /* 079E */
  X, /* 079F */
  X, /* 07A0 */
  X, /* 07A1 */
  X, /* 07A2 */
  X, /* 07A3 */
  X, /* 07A4 */
  X, /* 07A5 */
  X, /* 07A6 */
  X, /* 07A7 */
  X, /* 07A8 */
  X, /* 07A9 */
  X, /* 07AA */
  X, /* 07AB */
  X, /* 07AC */
  X, /* 07AD */
  X, /* 07AE */
  X, /* 07AF */
  X, /* 07B0 */
  X, /* 07B1 */
  X, /* 07B2 */
  X, /* 07B3 */
  X, /* 07B4 */
  X, /* 07B5 */
  X, /* 07B6 */
  X, /* 07B7 */
  X, /* 07B8 */
  X, /* 07B9 */
  X, /* 07BA */
  X, /* 07BB */
  X, /* 07BC */
  X, /* 07BD */
  X, /* 07BE */
  X, /* 07BF */

  /* NKo */

  X, /* 07C0 */
  X, /* 07C1 */
  X, /* 07C2 */
  X, /* 07C3 */
  X, /* 07C4 */
  X, /* 07C5 */
  X, /* 07C6 */
  X, /* 07C7 */
  X, /* 07C8 */
  X, /* 07C9 */
  D, /* 07CA; NKO A; D; No_Joining_Group */
  D, /* 07CB; NKO EE; D; No_Joining_Group */
  D, /* 07CC; NKO I; D; No_Joining_Group */
  D, /* 07CD; NKO E; D; No_Joining_Group */
  D, /* 07CE; NKO U; D; No_Joining_Group */
  D, /* 07CF; NKO OO; D; No_Joining_Group */
  D, /* 07D0; NKO O; D; No_Joining_Group */
  D, /* 07D1; NKO DAGBASINNA; D; No_Joining_Group */
  D, /* 07D2; NKO N; D; No_Joining_Group */
  D, /* 07D3; NKO BA; D; No_Joining_Group */
  D, /* 07D4; NKO PA; D; No_Joining_Group */
  D, /* 07D5; NKO TA; D; No_Joining_Group */
  D, /* 07D6; NKO JA; D; No_Joining_Group */
  D, /* 07D7; NKO CHA; D; No_Joining_Group */
  D, /* 07D8; NKO DA; D; No_Joining_Group */
  D, /* 07D9; NKO RA; D; No_Joining_Group */
  D, /* 07DA; NKO RRA; D; No_Joining_Group */
  D, /* 07DB; NKO SA; D; No_Joining_Group */
  D, /* 07DC; NKO GBA; D; No_Joining_Group */
  D, /* 07DD; NKO FA; D; No_Joining_Group */
  D, /* 07DE; NKO KA; D; No_Joining_Group */
  D, /* 07DF; NKO LA; D; No_Joining_Group */
  D, /* 07E0; NKO NA WOLOSO; D; No_Joining_Group */
  D, /* 07E1; NKO MA; D; No_Joining_Group */
  D, /* 07E2; NKO NYA; D; No_Joining_Group */
  D, /* 07E3; NKO NA; D; No_Joining_Group */
  D, /* 07E4; NKO HA; D; No_Joining_Group */
  D, /* 07E5; NKO WA; D; No_Joining_Group */
  D, /* 07E6; NKO YA; D; No_Joining_Group */
  D, /* 07E7; NKO NYA WOLOSO; D; No_Joining_Group */
  D, /* 07E8; NKO JONA JA; D; No_Joining_Group */
  D, /* 07E9; NKO JONA CHA; D; No_Joining_Group */
  D, /* 07EA; NKO JONA RA; D; No_Joining_Group */
  X, /* 07EB */
  X, /* 07EC */
  X, /* 07ED */
  X, /* 07EE */
  X, /* 07EF */
  X, /* 07F0 */
  X, /* 07F1 */
  X, /* 07F2 */
  X, /* 07F3 */
  X, /* 07F4 */
  X, /* 07F5 */
  X, /* 07F6 */
  X, /* 07F7 */
  X, /* 07F8 */
  X, /* 07F9 */
  C, /* 07FA; NKO LAJANYALAN; C; No_Joining_Group */
  X, /* 07FB */
  X, /* 07FC */
  X, /* 07FD */
  X, /* 07FE */
  X, /* 07FF */

  /* Samaritan */

  X, /* 0800 */
  X, /* 0801 */
  X, /* 0802 */
  X, /* 0803 */
  X, /* 0804 */
  X, /* 0805 */
  X, /* 0806 */
  X, /* 0807 */
  X, /* 0808 */
  X, /* 0809 */
  X, /* 080A */
  X, /* 080B */
  X, /* 080C */
  X, /* 080D */
  X, /* 080E */
  X, /* 080F */
  X, /* 0810 */
  X, /* 0811 */
  X, /* 0812 */
  X, /* 0813 */
  X, /* 0814 */
  X, /* 0815 */
  X, /* 0816 */
  X, /* 0817 */
  X, /* 0818 */
  X, /* 0819 */
  X, /* 081A */
  X, /* 081B */
  X, /* 081C */
  X, /* 081D */
  X, /* 081E */
  X, /* 081F */
  X, /* 0820 */
  X, /* 0821 */
  X, /* 0822 */
  X, /* 0823 */
  X, /* 0824 */
  X, /* 0825 */
  X, /* 0826 */
  X, /* 0827 */
  X, /* 0828 */
  X, /* 0829 */
  X, /* 082A */
  X, /* 082B */
  X, /* 082C */
  X, /* 082D */
  X, /* 082E */
  X, /* 082F */
  X, /* 0830 */
  X, /* 0831 */
  X, /* 0832 */
  X, /* 0833 */
  X, /* 0834 */
  X, /* 0835 */
  X, /* 0836 */
  X, /* 0837 */
  X, /* 0838 */
  X, /* 0839 */
  X, /* 083A */
  X, /* 083B */
  X, /* 083C */
  X, /* 083D */
  X, /* 083E */
  X, /* 083F */

  /* Mandaic */

  R, /* 0840; MANDAIC HALQA; R; No_Joining_Group */
  D, /* 0841; MANDAIC AB; D; No_Joining_Group */
  D, /* 0842; MANDAIC AG; D; No_Joining_Group */
  D, /* 0843; MANDAIC AD; D; No_Joining_Group */
  D, /* 0844; MANDAIC AH; D; No_Joining_Group */
  D, /* 0845; MANDAIC USHENNA; D; No_Joining_Group */
  R, /* 0846; MANDAIC AZ; R; No_Joining_Group */
  D, /* 0847; MANDAIC IT; D; No_Joining_Group */
  D, /* 0848; MANDAIC ATT; D; No_Joining_Group */
  R, /* 0849; MANDAIC AKSA; R; No_Joining_Group */
  D, /* 084A; MANDAIC AK; D; No_Joining_Group */
  D, /* 084B; MANDAIC AL; D; No_Joining_Group */
  D, /* 084C; MANDAIC AM; D; No_Joining_Group */
  D, /* 084D; MANDAIC AN; D; No_Joining_Group */
  D, /* 084E; MANDAIC AS; D; No_Joining_Group */
  R, /* 084F; MANDAIC IN; R; No_Joining_Group */
  D, /* 0850; MANDAIC AP; D; No_Joining_Group */
  D, /* 0851; MANDAIC ASZ; D; No_Joining_Group */
  D, /* 0852; MANDAIC AQ; D; No_Joining_Group */
  D, /* 0853; MANDAIC AR; D; No_Joining_Group */
  R, /* 0854; MANDAIC ASH; R; No_Joining_Group */
  D, /* 0855; MANDAIC AT; D; No_Joining_Group */
  U, /* 0856; MANDAIC DUSHENNA; U; No_Joining_Group */
  U, /* 0857; MANDAIC KAD; U; No_Joining_Group */
  U, /* 0858; MANDAIC AIN; U; No_Joining_Group */
  X, /* 0859 */
  X, /* 085A */
  X, /* 085B */
  X, /* 085C */
  X, /* 085D */
  X, /* 085E */
  X, /* 085F */
  X, /* 0860 */
  X, /* 0861 */
  X, /* 0862 */
  X, /* 0863 */
  X, /* 0864 */
  X, /* 0865 */
  X, /* 0866 */
  X, /* 0867 */
  X, /* 0868 */
  X, /* 0869 */
  X, /* 086A */
  X, /* 086B */
  X, /* 086C */
  X, /* 086D */
  X, /* 086E */
  X, /* 086F */
  X, /* 0870 */
  X, /* 0871 */
  X, /* 0872 */
  X, /* 0873 */
  X, /* 0874 */
  X, /* 0875 */
  X, /* 0876 */
  X, /* 0877 */
  X, /* 0878 */
  X, /* 0879 */
  X, /* 087A */
  X, /* 087B */
  X, /* 087C */
  X, /* 087D */
  X, /* 087E */
  X, /* 087F */
  X, /* 0880 */
  X, /* 0881 */
  X, /* 0882 */
  X, /* 0883 */
  X, /* 0884 */
  X, /* 0885 */
  X, /* 0886 */
  X, /* 0887 */
  X, /* 0888 */
  X, /* 0889 */
  X, /* 088A */
  X, /* 088B */
  X, /* 088C */
  X, /* 088D */
  X, /* 088E */
  X, /* 088F */
  X, /* 0890 */
  X, /* 0891 */
  X, /* 0892 */
  X, /* 0893 */
  X, /* 0894 */
  X, /* 0895 */
  X, /* 0896 */
  X, /* 0897 */
  X, /* 0898 */
  X, /* 0899 */
  X, /* 089A */
  X, /* 089B */
  X, /* 089C */
  X, /* 089D */
  X, /* 089E */
  X, /* 089F */

  /* Arabic Extended-A */

  D, /* 08A0; DOTLESS BEH WITH V BELOW; D; BEH */
  X, /* 08A1 */
  D, /* 08A2; HAH WITH DOT BELOW AND 2 DOTS ABOVE; D; HAH */
  D, /* 08A3; TAH WITH 2 DOTS ABOVE; D; TAH */
  D, /* 08A4; DOTLESS FEH WITH DOT BELOW AND 3 DOTS ABOVE; D; FEH */
  D, /* 08A5; QAF WITH DOT BELOW; D; QAF */
  D, /* 08A6; LAM WITH DOUBLE BAR; D; LAM */
  D, /* 08A7; MEEM WITH 3 DOTS ABOVE; D; MEEM */
  D, /* 08A8; YEH WITH HAMZA ABOVE; D; YEH */
  D, /* 08A9; YEH WITH DOT ABOVE; D; YEH */
  R, /* 08AA; REH WITH LOOP; R; REH */
  R, /* 08AB; WAW WITH DOT WITHIN; R; WAW */
  R, /* 08AC; ROHINGYA YEH; R; ROHINGYA YEH */

};

#define JOINING_TABLE_FIRST	0x0600
#define JOINING_TABLE_LAST	0x08AC

#undef X
#undef R
#undef U
#undef A
#undef DR
#undef C
#undef D


static const uint16_t shaping_table[][4] =
{
  {0x0000, 0x0000, 0x0000, 0xFE80}, /* U+0621 ARABIC LETTER HAMZA ISOLATED FORM */
  {0x0000, 0x0000, 0xFE82, 0xFE81}, /* U+0622 ARABIC LETTER ALEF WITH MADDA ABOVE */
  {0x0000, 0x0000, 0xFE84, 0xFE83}, /* U+0623 ARABIC LETTER ALEF WITH HAMZA ABOVE */
  {0x0000, 0x0000, 0xFE86, 0xFE85}, /* U+0624 ARABIC LETTER WAW WITH HAMZA ABOVE */
  {0x0000, 0x0000, 0xFE88, 0xFE87}, /* U+0625 ARABIC LETTER ALEF WITH HAMZA BELOW */
  {0xFE8B, 0xFE8C, 0xFE8A, 0xFE89}, /* U+0626 ARABIC LETTER YEH WITH HAMZA ABOVE */
  {0x0000, 0x0000, 0xFE8E, 0xFE8D}, /* U+0627 ARABIC LETTER ALEF */
  {0xFE91, 0xFE92, 0xFE90, 0xFE8F}, /* U+0628 ARABIC LETTER BEH */
  {0x0000, 0x0000, 0xFE94, 0xFE93}, /* U+0629 ARABIC LETTER TEH MARBUTA */
  {0xFE97, 0xFE98, 0xFE96, 0xFE95}, /* U+062A ARABIC LETTER TEH */
  {0xFE9B, 0xFE9C, 0xFE9A, 0xFE99}, /* U+062B ARABIC LETTER THEH */
  {0xFE9F, 0xFEA0, 0xFE9E, 0xFE9D}, /* U+062C ARABIC LETTER JEEM */
  {0xFEA3, 0xFEA4, 0xFEA2, 0xFEA1}, /* U+062D ARABIC LETTER HAH */
  {0xFEA7, 0xFEA8, 0xFEA6, 0xFEA5}, /* U+062E ARABIC LETTER KHAH */
  {0x0000, 0x0000, 0xFEAA, 0xFEA9}, /* U+062F ARABIC LETTER DAL */
  {0x0000, 0x0000, 0xFEAC, 0xFEAB}, /* U+0630 ARABIC LETTER THAL */
  {0x0000, 0x0000, 0xFEAE, 0xFEAD}, /* U+0631 ARABIC LETTER REH */
  {0x0000, 0x0000, 0xFEB0, 0xFEAF}, /* U+0632 ARABIC LETTER ZAIN */
  {0xFEB3, 0xFEB4, 0xFEB2, 0xFEB1}, /* U+0633 ARABIC LETTER SEEN */
  {0xFEB7, 0xFEB8, 0xFEB6, 0xFEB5}, /* U+0634 ARABIC LETTER SHEEN */
  {0xFEBB, 0xFEBC, 0xFEBA, 0xFEB9}, /* U+0635 ARABIC LETTER SAD */
  {0xFEBF, 0xFEC0, 0xFEBE, 0xFEBD}, /* U+0636 ARABIC LETTER DAD */
  {0xFEC3, 0xFEC4, 0xFEC2, 0xFEC1}, /* U+0637 ARABIC LETTER TAH */
  {0xFEC7, 0xFEC8, 0xFEC6, 0xFEC5}, /* U+0638 ARABIC LETTER ZAH */
  {0xFECB, 0xFECC, 0xFECA, 0xFEC9}, /* U+0639 ARABIC LETTER AIN */
  {0xFECF, 0xFED0, 0xFECE, 0xFECD}, /* U+063A ARABIC LETTER GHAIN */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+063B  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+063C  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+063D  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+063E  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+063F  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0640  */
  {0xFED3, 0xFED4, 0xFED2, 0xFED1}, /* U+0641 ARABIC LETTER FEH */
  {0xFED7, 0xFED8, 0xFED6, 0xFED5}, /* U+0642 ARABIC LETTER QAF */
  {0xFEDB, 0xFEDC, 0xFEDA, 0xFED9}, /* U+0643 ARABIC LETTER KAF */
  {0xFEDF, 0xFEE0, 0xFEDE, 0xFEDD}, /* U+0644 ARABIC LETTER LAM */
  {0xFEE3, 0xFEE4, 0xFEE2, 0xFEE1}, /* U+0645 ARABIC LETTER MEEM */
  {0xFEE7, 0xFEE8, 0xFEE6, 0xFEE5}, /* U+0646 ARABIC LETTER NOON */
  {0xFEEB, 0xFEEC, 0xFEEA, 0xFEE9}, /* U+0647 ARABIC LETTER HEH */
  {0x0000, 0x0000, 0xFEEE, 0xFEED}, /* U+0648 ARABIC LETTER WAW */
  {0xFBE8, 0xFBE9, 0xFEF0, 0xFEEF}, /* U+0649 ARABIC LETTER */
  {0xFEF3, 0xFEF4, 0xFEF2, 0xFEF1}, /* U+064A ARABIC LETTER YEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+064B  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+064C  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+064D  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+064E  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+064F  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0650  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0651  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0652  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0653  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0654  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0655  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0656  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0657  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0658  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0659  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+065A  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+065B  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+065C  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+065D  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+065E  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+065F  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0660  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0661  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0662  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0663  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0664  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0665  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0666  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0667  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0668  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0669  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+066A  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+066B  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+066C  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+066D  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+066E  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+066F  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0670  */
  {0x0000, 0x0000, 0xFB51, 0xFB50}, /* U+0671 ARABIC LETTER ALEF WASLA */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0672  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0673  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0674  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0675  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0676  */
  {0x0000, 0x0000, 0x0000, 0xFBDD}, /* U+0677 ARABIC LETTER U WITH HAMZA ABOVE ISOLATED FORM */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0678  */
  {0xFB68, 0xFB69, 0xFB67, 0xFB66}, /* U+0679 ARABIC LETTER TTEH */
  {0xFB60, 0xFB61, 0xFB5F, 0xFB5E}, /* U+067A ARABIC LETTER TTEHEH */
  {0xFB54, 0xFB55, 0xFB53, 0xFB52}, /* U+067B ARABIC LETTER BEEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+067C  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+067D  */
  {0xFB58, 0xFB59, 0xFB57, 0xFB56}, /* U+067E ARABIC LETTER PEH */
  {0xFB64, 0xFB65, 0xFB63, 0xFB62}, /* U+067F ARABIC LETTER TEHEH */
  {0xFB5C, 0xFB5D, 0xFB5B, 0xFB5A}, /* U+0680 ARABIC LETTER BEHEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0681  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0682  */
  {0xFB78, 0xFB79, 0xFB77, 0xFB76}, /* U+0683 ARABIC LETTER NYEH */
  {0xFB74, 0xFB75, 0xFB73, 0xFB72}, /* U+0684 ARABIC LETTER DYEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0685  */
  {0xFB7C, 0xFB7D, 0xFB7B, 0xFB7A}, /* U+0686 ARABIC LETTER TCHEH */
  {0xFB80, 0xFB81, 0xFB7F, 0xFB7E}, /* U+0687 ARABIC LETTER TCHEHEH */
  {0x0000, 0x0000, 0xFB89, 0xFB88}, /* U+0688 ARABIC LETTER DDAL */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0689  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+068A  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+068B  */
  {0x0000, 0x0000, 0xFB85, 0xFB84}, /* U+068C ARABIC LETTER DAHAL */
  {0x0000, 0x0000, 0xFB83, 0xFB82}, /* U+068D ARABIC LETTER DDAHAL */
  {0x0000, 0x0000, 0xFB87, 0xFB86}, /* U+068E ARABIC LETTER DUL */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+068F  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0690  */
  {0x0000, 0x0000, 0xFB8D, 0xFB8C}, /* U+0691 ARABIC LETTER RREH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0692  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0693  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0694  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0695  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0696  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0697  */
  {0x0000, 0x0000, 0xFB8B, 0xFB8A}, /* U+0698 ARABIC LETTER JEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+0699  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+069A  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+069B  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+069C  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+069D  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+069E  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+069F  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A0  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A1  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A2  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A3  */
  {0xFB6C, 0xFB6D, 0xFB6B, 0xFB6A}, /* U+06A4 ARABIC LETTER VEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A5  */
  {0xFB70, 0xFB71, 0xFB6F, 0xFB6E}, /* U+06A6 ARABIC LETTER PEHEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A7  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06A8  */
  {0xFB90, 0xFB91, 0xFB8F, 0xFB8E}, /* U+06A9 ARABIC LETTER KEHEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06AA  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06AB  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06AC  */
  {0xFBD5, 0xFBD6, 0xFBD4, 0xFBD3}, /* U+06AD ARABIC LETTER NG */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06AE  */
  {0xFB94, 0xFB95, 0xFB93, 0xFB92}, /* U+06AF ARABIC LETTER GAF */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B0  */
  {0xFB9C, 0xFB9D, 0xFB9B, 0xFB9A}, /* U+06B1 ARABIC LETTER NGOEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B2  */
  {0xFB98, 0xFB99, 0xFB97, 0xFB96}, /* U+06B3 ARABIC LETTER GUEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B4  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B5  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B6  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B7  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B8  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06B9  */
  {0x0000, 0x0000, 0xFB9F, 0xFB9E}, /* U+06BA ARABIC LETTER NOON GHUNNA */
  {0xFBA2, 0xFBA3, 0xFBA1, 0xFBA0}, /* U+06BB ARABIC LETTER RNOON */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06BC  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06BD  */
  {0xFBAC, 0xFBAD, 0xFBAB, 0xFBAA}, /* U+06BE ARABIC LETTER HEH DOACHASHMEE */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06BF  */
  {0x0000, 0x0000, 0xFBA5, 0xFBA4}, /* U+06C0 ARABIC LETTER HEH WITH YEH ABOVE */
  {0xFBA8, 0xFBA9, 0xFBA7, 0xFBA6}, /* U+06C1 ARABIC LETTER HEH GOAL */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06C2  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06C3  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06C4  */
  {0x0000, 0x0000, 0xFBE1, 0xFBE0}, /* U+06C5 ARABIC LETTER KIRGHIZ OE */
  {0x0000, 0x0000, 0xFBDA, 0xFBD9}, /* U+06C6 ARABIC LETTER OE */
  {0x0000, 0x0000, 0xFBD8, 0xFBD7}, /* U+06C7 ARABIC LETTER U */
  {0x0000, 0x0000, 0xFBDC, 0xFBDB}, /* U+06C8 ARABIC LETTER YU */
  {0x0000, 0x0000, 0xFBE3, 0xFBE2}, /* U+06C9 ARABIC LETTER KIRGHIZ YU */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06CA  */
  {0x0000, 0x0000, 0xFBDF, 0xFBDE}, /* U+06CB ARABIC LETTER VE */
  {0xFBFE, 0xFBFF, 0xFBFD, 0xFBFC}, /* U+06CC ARABIC LETTER FARSI YEH */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06CD  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06CE  */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06CF  */
  {0xFBE6, 0xFBE7, 0xFBE5, 0xFBE4}, /* U+06D0 ARABIC LETTER E */
  {0x0000, 0x0000, 0x0000, 0x0000}, /* U+06D1  */
  {0x0000, 0x0000, 0xFBAF, 0xFBAE}, /* U+06D2 ARABIC LETTER YEH BARREE */
  {0x0000, 0x0000, 0xFBB1, 0xFBB0}, /* U+06D3 ARABIC LETTER YEH BARREE WITH HAMZA ABOVE */
};

#define SHAPING_TABLE_FIRST	0x0621
#define SHAPING_TABLE_LAST	0x06D3


static const struct ligature_set_t {
 uint16_t first;
 struct ligature_pairs_t {
   uint16_t second;
   uint16_t ligature;
 } ligatures[4];
} ligature_table[] =
{
  { 0xFEDF, {
    { 0xFE88, 0xFEF9 }, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM */
    { 0xFE82, 0xFEF5 }, /* ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM */
    { 0xFE8E, 0xFEFB }, /* ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM */
    { 0xFE84, 0xFEF7 }, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM */
  }},
  { 0xFEE0, {
    { 0xFE88, 0xFEFA }, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM */
    { 0xFE82, 0xFEF6 }, /* ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM */
    { 0xFE8E, 0xFEFC }, /* ARABIC LIGATURE LAM WITH ALEF FINAL FORM */
    { 0xFE84, 0xFEF8 }, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM */
  }},
};


#endif /* HB_OT_SHAPE_COMPLEX_ARABIC_TABLE_HH */

/* == End of generated table == */
