TOP = ..\..\..
!INCLUDE $(TOP)\glib\build\win32\make.msc

INCLUDES = -I . -I ..\.. $(FREETYPE2_CFLAGS) $(GLIB_CFLAGS)
DEFINES = -DPANGO_ENABLE_ENGINE

OBJECTS = \
	ftglue.obj \
	harfbuzz-buffer.obj \
	harfbuzz-gdef.obj \
	harfbuzz-gpos.obj \
	harfbuzz-gsub.obj \
	harfbuzz-open.obj \

all : \
	pango-ot.lib

pango-ot.lib : $(OBJECTS)
	lib /out:$@ $(OBJECTS)	