#!/usr/bin/python

import sys

red_color = '\033[41;37;1m'
green_color = '\033[42;37;1m'
end_color = '\033[m'

def filter_failures (f):
	for l in f:
		if l[0] in '-+':
			sys.stdout.writelines (l)
			continue


def open_file (f):
	if f == '-':
		return sys.stdin
	return file (f)

if __name__ == '__main__':

	if len (sys.argv) == 1:
		print "Usage: %s FILE..." % sys.argv[0]
		sys.exit (1)

	for s in sys.argv[1:]:
		filter_failures (open_file (s))
