#!/usr/bin/python

from hb_test_tools import *
import sys, os

if len (sys.argv) < 3:
	print "usage: %s file1 file2..." % sys.argv[0]
	sys.exit (1)

ZipDiffer.diff_files (FileHelpers.open_file_or_stdin (f) for f in sys.argv[1:])
