#!/bin/sh

if test $# = 0; then
	echo "Usage: $0 DIR..."
	exit 1
fi

find "$@" -type d |
while read d; do
	echo "  GEN    $d/MANIFEST";
	(
		cd "$d" &&
		ls |
		grep -v "MANIFEST\|README\|LICENSE\|COPYING\|SOURCE" |
		LANG=C sort > MANIFEST.tmp &&
		mv MANIFEST.tmp MANIFEST ||
		(
			rm -f MANIFEST.tmp
			false
		)
	)
done
